.TH "/home/jhuston/Dropbox/School/OPENGL/HSC/Util/wiic_r90/src/wiic/ Directory Reference" 3 "Sun Dec 2 2012" "Version 001" "OpenGL Flythrough" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/jhuston/Dropbox/School/OPENGL/HSC/Util/wiic_r90/src/wiic/ Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBbalanceboard\&.c\fP"
.br
.ti -1c
.RI "file \fBbalanceboard\&.h\fP"
.br
.RI "\fIBalance Board expansion device\&. \fP"
.ti -1c
.RI "file \fBclassic\&.c\fP"
.br
.RI "\fIClassic controller expansion device\&. \fP"
.ti -1c
.RI "file \fBclassic\&.h\fP"
.br
.RI "\fIClassic controller expansion device\&. \fP"
.ti -1c
.RI "file \fBdefinitions\&.h\fP"
.br
.RI "\fIGeneral definitions\&. \fP"
.ti -1c
.RI "file \fBdynamics\&.c\fP"
.br
.RI "\fIHandles the dynamics of the wiimote\&. \fP"
.ti -1c
.RI "file \fBdynamics\&.h\fP"
.br
.RI "\fIHandles the dynamics of the wiimote\&. \fP"
.ti -1c
.RI "file \fBevents\&.c\fP"
.br
.RI "\fIHandles wiimote events\&. \fP"
.ti -1c
.RI "file \fBevents\&.h\fP"
.br
.RI "\fIHandles wiimote events\&. \fP"
.ti -1c
.RI "file \fBguitar_hero_3\&.c\fP"
.br
.RI "\fIGuitar Hero 3 expansion device\&. \fP"
.ti -1c
.RI "file \fBguitar_hero_3\&.h\fP"
.br
.RI "\fIGuitar Hero 3 expansion device\&. \fP"
.ti -1c
.RI "file \fBio\&.c\fP"
.br
.RI "\fIHandles device I/O (non-OS specific)\&. \fP"
.ti -1c
.RI "file \fBio\&.h\fP"
.br
.RI "\fIHandles device I/O\&. \fP"
.ti -1c
.RI "file \fBio_mac\&.h\fP"
.br
.RI "\fII/O header file for MacOS\&. \fP"
.ti -1c
.RI "file \fBio_mac\&.m\fP"
.br
.RI "\fIHandles device I/O for Mac\&. \fP"
.ti -1c
.RI "file \fBio_nix\&.c\fP"
.br
.RI "\fIHandles device I/O for *nix\&. \fP"
.ti -1c
.RI "file \fBir\&.c\fP"
.br
.RI "\fIHandles IR data\&. \fP"
.ti -1c
.RI "file \fBir\&.h\fP"
.br
.RI "\fIHandles IR data\&. \fP"
.ti -1c
.RI "file \fBmotionplus\&.c\fP"
.br
.RI "\fIMotion Plus expansion device\&. \fP"
.ti -1c
.RI "file \fBmotionplus\&.h\fP"
.br
.RI "\fIMotion Plus expansion device\&. \fP"
.ti -1c
.RI "file \fBnunchuk\&.c\fP"
.br
.RI "\fINunchuk expansion device\&. \fP"
.ti -1c
.RI "file \fBnunchuk\&.h\fP"
.br
.RI "\fINunchuk expansion device\&. \fP"
.ti -1c
.RI "file \fBspeaker\&.c\fP"
.br
.RI "\fIHandles the Wiimote speakers\&. \fP"
.ti -1c
.RI "file \fBspeaker\&.h\fP"
.br
.RI "\fIHandles the Wiimote speakers\&. \fP"
.ti -1c
.RI "file \fBwiic\&.c\fP"
.br
.RI "\fIGeneral wiimote operations\&. \fP"
.ti -1c
.RI "file \fBwiic\&.h\fP"
.br
.RI "\fIAPI header file\&. \fP"
.ti -1c
.RI "file \fBwiic_doc\&.h\fP"
.br
.ti -1c
.RI "file \fBwiic_functions\&.h\fP"
.br
.RI "\fIWiiC public functions\&. \fP"
.ti -1c
.RI "file \fBwiic_internal\&.h\fP"
.br
.RI "\fIGeneral internal wiic stuff\&. \fP"
.ti -1c
.RI "file \fBwiic_macros\&.h\fP"
.br
.RI "\fIWiiC macros and typedef\&. \fP"
.ti -1c
.RI "file \fBwiic_structs\&.h\fP"
.br
.RI "\fIWiiC structures\&. \fP"
.in -1c
