.TH "/home/jhuston/Dropbox/School/OPENGL/HSC/Util/wiic_r90/ Directory Reference" 3 "Fri Nov 30 2012" "Version 001" "OpenGL Flythrough" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/jhuston/Dropbox/School/OPENGL/HSC/Util/wiic_r90/ Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBsrc\fP"
.br
.in -1c
