.TH "/home/nago/Dropbox/School/OPENGL/HSC/master/Util/wiic_r90/ Directory Reference" 3 "Tue Dec 18 2012" "Version 9001" "OpenGL Flythrough" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/nago/Dropbox/School/OPENGL/HSC/master/Util/wiic_r90/ Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBbuild\fP"
.br
.ti -1c
.RI "directory \fBsrc\fP"
.br
.in -1c
