.TH "accel_t" 3 "Tue Dec 18 2012" "Version 9001" "OpenGL Flythrough" \" -*- nroff -*-
.ad l
.nh
.SH NAME
accel_t \- 
.PP
Accelerometer struct\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <wiic_structs\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "struct \fBvec3b_t\fP \fBcal_zero\fP"
.br
.RI "\fIzero calibration \fP"
.ti -1c
.RI "struct \fBvec3b_t\fP \fBcal_g\fP"
.br
.RI "\fI1g difference around 0cal \fP"
.ti -1c
.RI "float \fBst_alpha\fP"
.br
.RI "\fIalpha value for smoothing [0-1] \fP"
.in -1c
.SH "Detailed Description"
.PP 
Accelerometer struct\&. 

For any device with an accelerometer\&. 
.PP
Definition at line 147 of file wiic_structs\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for OpenGL Flythrough from the source code\&.
