.TH "AccSample" 3 "Sun Dec 9 2012" "Version 9001" "OpenGL Flythrough" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AccSample \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBSample\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAccSample\fP (float x, float y, float z)"
.br
.ti -1c
.RI "\fBAccSample\fP (const string &line)"
.br
.ti -1c
.RI "float \fBx\fP () const "
.br
.ti -1c
.RI "float \fBy\fP () const "
.br
.ti -1c
.RI "float \fBz\fP () const "
.br
.ti -1c
.RI "virtual void \fBsave\fP (ofstream &out)"
.br
.ti -1c
.RI "void \fBsetLogType\fP (int l)"
.br
.ti -1c
.RI "int \fBgetLogType\fP () const "
.br
.ti -1c
.RI "void \fBsetTimestampFromGestureStart\fP (unsigned long t)"
.br
.ti -1c
.RI "unsigned long \fBgetTimestampFromGestureStart\fP () const "
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "unsigned long \fBrelTimestamp\fP"
.br
.ti -1c
.RI "int \fBlogType\fP"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "float \fBax\fP"
.br
.ti -1c
.RI "float \fBay\fP"
.br
.ti -1c
.RI "float \fBaz\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 6 of file accsample\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for OpenGL Flythrough from the source code\&.
