.TH "ang3s_t" 3 "Sat Dec 1 2012" "Version 001" "OpenGL Flythrough" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ang3s_t \- 
.PP
RPY short int angles\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <wiic_structs\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "short \fBroll\fP"
.br
.ti -1c
.RI "short \fBpitch\fP"
.br
.ti -1c
.RI "short \fByaw\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
RPY short int angles\&. 
.PP
Definition at line 91 of file wiic_structs\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for OpenGL Flythrough from the source code\&.
