.TH "ang_rate_t" 3 "Mon Dec 3 2012" "Version 001" "OpenGL Flythrough" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ang_rate_t \- 
.PP
Angular rate struct\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <wiic_structs\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "struct \fBang3f_t\fP \fBrate\fP"
.br
.RI "\fIroll, pitch and yaw rate (this may be smoothed if enabled) \fP"
.ti -1c
.RI "struct \fBang3f_t\fP \fBa_rate\fP"
.br
.RI "\fIroll, pitch and yaw rate (unsmoothed) \fP"
.in -1c
.SH "Detailed Description"
.PP 
Angular rate struct\&. 

Yaw, pitch, and roll rate from -180 to 180 degrees\&. 
.PP
Definition at line 119 of file wiic_structs\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for OpenGL Flythrough from the source code\&.
