.TH "Camera" 3 "Tue Dec 18 2012" "Version 9001" "OpenGL Flythrough" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Camera \- 
.PP
The \fBCamera\fP class represents a logical camera in a model view, which posesses a current viewing angle and an absolute position in space as its state\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Camera\&.hpp>\fP
.PP
Inherits \fBObject\fP\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBDirection\fP { \fBForward\fP, \fBBackward\fP, \fBLeft\fP, \fBRight\fP, \fBUp\fP, \fBDown\fP, \fBDirection_End\fP, \fBDirection_Begin\fP =  Forward }"
.br
.RI "\fIThe Direction enumeration lists all of the possible directions the camera may travel in\&. \fP"
.ti -1c
.RI "enum \fBview_type\fP { \fBPERSPECTIVE\fP, \fBORTHO\fP, \fBORTHO2D\fP, \fBIDENTITY\fP, \fBFRUSTUM\fP }"
.br
.RI "\fIThe view_type enumeration lists the various possibilities for the current viewing mode that can be switched between\&. \fP"
.ti -1c
.RI "enum \fBUniforms\fP { \fBBegin\fP =  Object::End, \fBTRANSLATION\fP =  Begin, \fBROTATION\fP, \fBVIEW\fP, \fBCTM\fP, \fBEnd\fP }"
.br
.RI "\fIThe glsl_var enumeration lists the various variables the \fBCamera\fP class is capable of sending to the shader\&. \fP"
.ti -1c
.RI "typedef enum \fBCamera::Uniforms\fP \fBUniform\fP"
.br
.RI "\fIThe glsl_var enumeration lists the various variables the \fBCamera\fP class is capable of sending to the shader\&. \fP"
.ti -1c
.RI "typedef const unsigned int \fBUniformEnum\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCamera\fP (const std::string &\fBname\fP, GLuint gShader, float x=0\&.0, float y=0\&.0, float z=0\&.0)"
.br
.RI "\fIInitialization Constructor; sets the X,Y,Z coordinates explicitly\&. \fP"
.ti -1c
.RI "\fBCamera\fP (const std::string &\fBname\fP, GLuint gShader, \fBvec3\fP &in)"
.br
.RI "\fIInitialization Constructor, uses a vec3 as its initial coordinates\&. \fP"
.ti -1c
.RI "\fBCamera\fP (const std::string &\fBname\fP, GLuint gShader, \fBvec4\fP &in)"
.br
.RI "\fIInitialization Constructor, uses a vec4 as its initial coordinates\&. \fP"
.ti -1c
.RI "virtual \fB~Camera\fP (void)"
.br
.RI "\fIDefault destructor\&. \fP"
.ti -1c
.RI "void \fBX\fP (const float &in, const bool &update=true)"
.br
.RI "\fISets the X coordinate of the camera\&. \fP"
.ti -1c
.RI "void \fBY\fP (const float &in, const bool &update=true)"
.br
.RI "\fISets the Y coordinate of the camera\&. \fP"
.ti -1c
.RI "void \fBZ\fP (const float &in, const bool &update=true)"
.br
.RI "\fISets the Z coordinate of the camera\&. \fP"
.ti -1c
.RI "void \fBpos\fP (const float &x, const float &y, const float &z, const bool &update=true)"
.br
.RI "\fISets the absolute position of the camera\&. \fP"
.ti -1c
.RI "void \fBpos\fP (const \fBvec3\fP &in, const bool &update=true)"
.br
.RI "\fISets the absolute position of the camera\&. \fP"
.ti -1c
.RI "void \fBpos\fP (const \fBvec4\fP &in, const bool &update=true)"
.br
.RI "\fISets the absolute position of the camera\&. \fP"
.ti -1c
.RI "void \fBdX\fP (const float &by, const bool &update=true)"
.br
.RI "\fIMoves the camera along the X axis\&. \fP"
.ti -1c
.RI "void \fBdY\fP (const float &by, const bool &update=true)"
.br
.RI "\fIMoves the camera along the Y axis\&. \fP"
.ti -1c
.RI "void \fBdZ\fP (const float &by, const bool &update=true)"
.br
.RI "\fIMoves the camera along the Z axis\&. \fP"
.ti -1c
.RI "void \fBdPos\fP (const float &x, const float &y, const float &z)"
.br
.RI "\fIMoves the camera along the x, y, and z axes\&. \fP"
.ti -1c
.RI "void \fBdPos\fP (const \fBvec3\fP &by)"
.br
.RI "\fIMoves the camera along the x, y, and z axes\&. \fP"
.ti -1c
.RI "void \fBdPos\fP (const \fBvec4\fP &by)"
.br
.RI "\fIMoves the camera along the x, y, and z axes\&. \fP"
.ti -1c
.RI "void \fBFOV\fP (const float &\fBfovy\fP)"
.br
.RI "\fIFOV sets the current camera Field-of-view angle\&. \fP"
.ti -1c
.RI "float \fBFOV\fP (void) const "
.br
.RI "\fI\fBFOV()\fP gets the current camera Field-of-view angle\&. \fP"
.ti -1c
.RI "void \fBdFOV\fP (const float &by)"
.br
.RI "\fIdFOV adjusts the field of view angle up or down by an amount\&. \fP"
.ti -1c
.RI "void \fBchangePerspective\fP (const \fBview_type\fP &vType)"
.br
.RI "\fIchangePerspective changes the current perspective of the camera\&. \fP"
.ti -1c
.RI "void \fBrefreshPerspective\fP (void)"
.br
.RI "\fIrefreshPerspective re-generates the current view/perspective matrix of the camera\&. \fP"
.ti -1c
.RI "void \fBviewport\fP (size_t _X, size_t _Y, size_t _width, size_t _height)"
.br
.RI "\fIviewport instructs this camera what his expected drawing window will be\&. \fP"
.ti -1c
.RI "void \fBsway\fP (const float &by)"
.br
.RI "\fIAdjusts the camera's X coordinate relative to its current position\&. \fP"
.ti -1c
.RI "void \fBsurge\fP (const float &by)"
.br
.RI "\fIAdjusts the camera's Z coordinate relative to its current position\&. \fP"
.ti -1c
.RI "void \fBheave\fP (const float &by)"
.br
.RI "\fIAdjusts the camera's Y coordinate relative to its current position\&. \fP"
.ti -1c
.RI "void \fBpitch\fP (const float &by, const bool &fixed=false)"
.br
.RI "\fIpitch adjusts the X axis rotation; up/down look\&. \fP"
.ti -1c
.RI "void \fByaw\fP (const float &by, const bool &fixed=false)"
.br
.RI "\fIyaw adjusts the Y axis rotation; left/right look\&. \fP"
.ti -1c
.RI "void \fBroll\fP (const float &by, const bool &fixed=false)"
.br
.RI "\fIroll adjusts the Z axis rotation; tilt or lean left/right\&. \fP"
.ti -1c
.RI "void \fBMove\fP (const \fBCamera::Direction\fP &Dir)"
.br
.RI "\fIMove instructs the camera to begin moving in the specified direction\&. \fP"
.ti -1c
.RI "void \fBStop\fP (const \fBCamera::Direction\fP &Dir)"
.br
.RI "\fIStop instructs the camera to stop moving in the specified direction\&. \fP"
.ti -1c
.RI "void \fBIdle\fP (void)"
.br
.RI "\fIIdle moves the camera forward in whichever directions it is configured to move in\&. \fP"
.ti -1c
.RI "void \fBAccel\fP (const \fBvec3\fP &accel)"
.br
.RI "\fIAccel takes an input vec2 which represents an acceleration, and applies it to the motion vectors with regards to the maximum acceleration and the maximum speed of the camera\&. \fP"
.ti -1c
.RI "float \fBX\fP (void) const "
.br
.RI "\fI\fBX()\fP returns the current position of the camera in model coordinates\&. \fP"
.ti -1c
.RI "float \fBY\fP (void) const "
.br
.RI "\fI\fBY()\fP returns the current position of the camera in model coordinates\&. \fP"
.ti -1c
.RI "float \fBZ\fP (void) const "
.br
.RI "\fI\fBZ()\fP returns the current position of the camera in model coordinates\&. \fP"
.ti -1c
.RI "\fBvec4\fP \fBpos\fP (void) const "
.br
.RI "\fI\fBpos()\fP gets the current camera position in model coordinates\&. \fP"
.ti -1c
.RI "virtual void \fBSend\fP (Object::UniformEnum which)"
.br
.RI "\fIsend will send a glsl variable to the shader\&. \fP"
.ti -1c
.RI "void \fBView\fP (void)"
.br
.RI "\fIView will instruct OpenGL of the viewport we want, and then send all of our current matrices to the shader for rendering\&. \fP"
.ti -1c
.RI "void \fBresetRotation\fP (void)"
.br
.ti -1c
.RI "void \fBDraw\fP (void)"
.br
.ti -1c
.RI "void \fBBuffer\fP (void)"
.br
.ti -1c
.RI "void \fBMode\fP (GLenum new_node)"
.br
.ti -1c
.RI "void \fBTexture\fP (const char **filename)"
.br
.ti -1c
.RI "const std::string & \fBName\fP (void) const "
.br
.ti -1c
.RI "virtual void \fBLink\fP (UniformEnum which, const std::string &\fBname\fP)"
.br
.ti -1c
.RI "void \fBAnimation\fP (void(*anim_func)(\fBTransCache\fP &arg))"
.br
.ti -1c
.RI "void \fBPropegate\fP (void)"
.br
.ti -1c
.RI "void \fBSetShader\fP (GLuint gShader)"
.br
.ti -1c
.RI "GLuint \fBGetShader\fP (void)"
.br
.ti -1c
.RI "\fBObject\fP * \fBAddObject\fP (const std::string &objName)"
.br
.ti -1c
.RI "void \fBDelObject\fP (const std::string &objName)"
.br
.ti -1c
.RI "void \fBDelObject\fP (void)"
.br
.ti -1c
.RI "void \fBPopObject\fP (void)"
.br
.ti -1c
.RI "void \fBDestroyObject\fP (void)"
.br
.RI "\fICompletely remove this object and all his children\&. \fP"
.ti -1c
.RI "\fBObject\fP * \fBNext\fP (void)"
.br
.ti -1c
.RI "\fBObject\fP * \fBPrev\fP (void)"
.br
.ti -1c
.RI "\fBObject\fP * \fBActive\fP (void)"
.br
.ti -1c
.RI "\fBObject\fP * \fBoperator[]\fP (const std::string &objname)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::vector< \fBAngel::vec4\fP > \fBpoints\fP"
.br
.ti -1c
.RI "std::vector< \fBAngel::vec3\fP > \fBnormals\fP"
.br
.ti -1c
.RI "std::vector< unsigned int > \fBindices\fP"
.br
.ti -1c
.RI "std::vector< \fBAngel::vec4\fP > \fBcolors\fP"
.br
.ti -1c
.RI "std::vector< \fBAngel::vec2\fP > \fBtexcoords\fP"
.br
.ti -1c
.RI "\fBTransCache\fP \fBtrans\fP"
.br
.RI "\fI\fBTransformation\fP State\&. \fP"
.ti -1c
.RI "std::vector< GLint > \fBhandles\fP"
.br
.RI "\fIHandles to Uniforms on the shader\&. \fP"
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBDeleteObject\fP (\fBObject\fP *obj)"
.br
.RI "\fIDeleteObject is the actual implementation function that will remove an \fBObject\fP from the \fBScene\fP list and \fBScene\fP map, then free the object\&. \fP"
.ti -1c
.RI "void \fBInsertObject\fP (const std::string \fBname\fP, \fBObject\fP *obj)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "std::string \fBname\fP"
.br
.RI "\fIname is used as an identifying handle for the object\&. \fP"
.ti -1c
.RI "GLuint \fBvao\fP"
.br
.RI "\fIVertex Array \fBObject\fP handle identifying our buffers/object\&. \fP"
.ti -1c
.RI "GLuint \fBbuffer\fP [5]"
.br
.RI "\fIHandles to our five buffers\&. \fP"
.ti -1c
.RI "GLenum \fBdraw_mode\fP"
.br
.RI "\fIDrawing mode for this object\&. \fP"
.ti -1c
.RI "bool \fBisTextured\fP"
.br
.ti -1c
.RI "std::list< \fBObject\fP * > \fBlist\fP"
.br
.ti -1c
.RI "std::map< std::string, \fBObject\fP * > \fBmap\fP"
.br
.ti -1c
.RI "std::list< \fBObject\fP * >::iterator \fBcurrentObj\fP"
.br
.ti -1c
.RI "GLuint \fBgShader\fP"
.br
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "void \fBadjustRotation\fP (const \fBmat4\fP &adjustment, const bool &fixed=false)"
.br
.RI "\fIadjustRotation is an internal function that rotates the camera\&. \fP"
.ti -1c
.RI "void \fBcommonInit\fP (void)"
.br
.RI "\fIcommonInit is a private function that initializes local object attributes\&. \fP"
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fBmat4\fP \fBT\fP"
.br
.RI "\fIThe current translation matrix for this camera\&. \fP"
.ti -1c
.RI "\fBmat4\fP \fBR\fP"
.br
.RI "\fIThe current rotational matrix for this camera\&. \fP"
.ti -1c
.RI "\fBmat4\fP \fBP\fP"
.br
.RI "\fIThe current view matrix (usually perspective) for this camera\&. \fP"
.ti -1c
.RI "\fBmat4\fP \fBctm\fP"
.br
.RI "\fIThe 'Current \fBTransformation\fP Matrix' for this camera\&. \fP"
.ti -1c
.RI "\fBview_type\fP \fBcurrView\fP"
.br
.RI "\fIThe current viewing mode type\&. \fP"
.ti -1c
.RI "GLfloat \fBspeed\fP"
.br
.RI "\fICurrent Speed of camera motion\&. \fP"
.ti -1c
.RI "\fBvec3\fP \fBvelocity\fP"
.br
.RI "\fICurrent Velocity of camera motion\&. \fP"
.ti -1c
.RI "GLfloat \fBspeed_cap\fP"
.br
.RI "\fICurrent Speed Capacity: (speed/MaxSpeed) \fP"
.ti -1c
.RI "GLfloat \fBMaxAccel\fP"
.br
.RI "\fIMaximum Acceleration Magnitude\&. \fP"
.ti -1c
.RI "GLfloat \fBMaxSpeed\fP"
.br
.RI "\fIMaximum Speed\&. \fP"
.ti -1c
.RI "GLfloat \fBFrictionMagnitude\fP"
.br
.RI "\fIFriction\&. \fP"
.ti -1c
.RI "GLfloat \fBaspect\fP"
.br
.RI "\fICurrent aspect ratio for certain perspectives\&. \fP"
.ti -1c
.RI "GLfloat \fBfovy\fP"
.br
.RI "\fICurrent field-of-view angle for perspective view\&. \fP"
.ti -1c
.RI "\fBAngel::vec2\fP \fBsize\fP"
.br
.RI "\fI\fBCamera\fP's Drawbox Width and Height\&. \fP"
.ti -1c
.RI "\fBAngel::vec2\fP \fBposition\fP"
.br
.RI "\fI\fBCamera\fP's Drawbox X,Y Coordinate (Upper-Left Pixel) \fP"
.ti -1c
.RI "bool \fBMotion\fP [Camera::Direction_End]"
.br
.RI "\fIBooleans correlating to the different motion directions\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
The \fBCamera\fP class represents a logical camera in a model view, which posesses a current viewing angle and an absolute position in space as its state\&. 

\fBAuthor:\fP
.RS 4
John Huston, jhuston@cs.uml.edu 
.RE
.PP
\fBSince:\fP
.RS 4
16 Nov 2012
.RE
.PP
Functions are provided to adjust the rotation according to \fBpitch()\fP, \fByaw()\fP and \fBroll()\fP motions; \fBsurge()\fP, \fBsway()\fP, and \fBheave()\fP are provided to adjust position in space\&.
.PP
\fBMove()\fP, \fBStop()\fP, and \fBIdle()\fP are provided to help the camera automatically move along the X, Y, or Z axes\&. 
.PP
Definition at line 31 of file Camera\&.hpp\&.
.SH "Member Typedef Documentation"
.PP 
.SS "typedef enum \fBCamera::Uniforms\fP  \fBCamera::Uniform\fP"

.PP
The glsl_var enumeration lists the various variables the \fBCamera\fP class is capable of sending to the shader\&. The NumGlslVars variable is a sentinel value that is ignored by any functions that accept a glsl_var\&. 
.SH "Member Enumeration Documentation"
.PP 
.SS "enum \fBCamera::Direction\fP"

.PP
The Direction enumeration lists all of the possible directions the camera may travel in\&. 'Begin' and 'End' are special sentinel directions for the purposes of iteration, and are ignored by any functions that accept a Direction\&. 
.PP
Definition at line 41 of file Camera\&.hpp\&.
.SS "enum \fBCamera::Uniforms\fP"

.PP
The glsl_var enumeration lists the various variables the \fBCamera\fP class is capable of sending to the shader\&. The NumGlslVars variable is a sentinel value that is ignored by any functions that accept a glsl_var\&. 
.PP
Definition at line 73 of file Camera\&.hpp\&.
.SS "enum \fBCamera::view_type\fP"

.PP
The view_type enumeration lists the various possibilities for the current viewing mode that can be switched between\&. The default is PERSPECTIVE\&. 
.PP
Definition at line 58 of file Camera\&.hpp\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Camera::Camera (const std::string &name, GLuintgShader, floatx = \fC0\&.0\fP, floaty = \fC0\&.0\fP, floatz = \fC0\&.0\fP)"

.PP
Initialization Constructor; sets the X,Y,Z coordinates explicitly\&. \fBParameters:\fP
.RS 4
\fIx\fP The initial X coordinate\&. 
.br
\fIy\fP The initial Y coordinate\&. 
.br
\fIz\fP The initial Z coordinate\&. 
.RE
.PP

.PP
Definition at line 67 of file Camera\&.cpp\&.
.SS "Camera::Camera (const std::string &name, GLuintgShader, \fBvec3\fP &in)"

.PP
Initialization Constructor, uses a vec3 as its initial coordinates\&. \fBParameters:\fP
.RS 4
\fIin\fP A vec3 representing the initial coordinates\&. 
.RE
.PP

.PP
Definition at line 79 of file Camera\&.cpp\&.
.SS "Camera::Camera (const std::string &name, GLuintgShader, \fBvec4\fP &in)"

.PP
Initialization Constructor, uses a vec4 as its initial coordinates\&. \fBParameters:\fP
.RS 4
\fIin\fP A vec4 representing the initial coordinates\&. The w component is ignored\&. 
.RE
.PP

.PP
Definition at line 90 of file Camera\&.cpp\&.
.SS "Camera::~Camera (void)\fC [virtual]\fP"

.PP
Default destructor\&. Nothing of note\&. 
.PP
Definition at line 100 of file Camera\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "void Camera::Accel (const \fBvec3\fP &raw_accel)"

.PP
Accel takes an input vec2 which represents an acceleration, and applies it to the motion vectors with regards to the maximum acceleration and the maximum speed of the camera\&. \fBParameters:\fP
.RS 4
\fIraw_accel\fP The vec3 which represents the (x,y,z) acceleration, where x,y,z are [-1,1]\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
Void\&. 
.RE
.PP

.PP
Definition at line 411 of file Camera\&.cpp\&.
.SS "void Camera::adjustRotation (const \fBmat4\fP &adjustment, const bool &fixed = \fCfalse\fP)\fC [private]\fP"

.PP
adjustRotation is an internal function that rotates the camera\&. Technically, any transformation, not just a rotation, is possible\&. 
.PP
\fBParameters:\fP
.RS 4
\fIadjustment\fP The 4x4 matrix to transform the CTM by\&. 
.br
\fIfixed\fP Should this rotation be fixed about the origin? 
.RE
.PP
\fBReturns:\fP
.RS 4
Void\&. 
.RE
.PP

.PP
Definition at line 275 of file Camera\&.cpp\&.
.SS "void Camera::changePerspective (const \fBview_type\fP &vType)"

.PP
changePerspective changes the current perspective of the camera\&. \fBParameters:\fP
.RS 4
\fIvType\fP Which perspective to use\&. see enum view_type for possibilities\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
Void\&. 
.RE
.PP

.PP
Definition at line 604 of file Camera\&.cpp\&.
.SS "void Camera::commonInit (void)\fC [private]\fP"

.PP
commonInit is a private function that initializes local object attributes\&. It should be called by all available constructors\&. 
.PP
\fBReturns:\fP
.RS 4
Void\&. 
.RE
.PP

.PP
Definition at line 34 of file Camera\&.cpp\&.
.SS "void Scene::DeleteObject (\fBObject\fP *obj)\fC [protected]\fP, \fC [inherited]\fP"

.PP
DeleteObject is the actual implementation function that will remove an \fBObject\fP from the \fBScene\fP list and \fBScene\fP map, then free the object\&. \fBParameters:\fP
.RS 4
\fIobj\fP The pointer to the object to free\&. 
.RE
.PP

.PP
Definition at line 50 of file Scene\&.cpp\&.
.SS "void Camera::dFOV (const float &by)"

.PP
dFOV adjusts the field of view angle up or down by an amount\&. \fBParameters:\fP
.RS 4
\fIby\fP The float to adjust the FOV angle by\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
Void\&. 
.RE
.PP

.PP
Definition at line 649 of file Camera\&.cpp\&.
.SS "void Camera::dPos (const float &x, const float &y, const float &z)"

.PP
Moves the camera along the x, y, and z axes\&. \fBParameters:\fP
.RS 4
\fIx\fP the X-axis displacement\&. 
.br
\fIy\fP the Y-axis displacement\&. 
.br
\fIz\fP the Z-axis displacement\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
Void\&. 
.RE
.PP

.PP
Definition at line 238 of file Camera\&.cpp\&.
.SS "void Camera::dPos (const \fBvec3\fP &by)"

.PP
Moves the camera along the x, y, and z axes\&. \fBParameters:\fP
.RS 4
\fIby\fP A vec3 containing the X, Y, and Z axis displacements\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
Void\&. 
.RE
.PP

.PP
Definition at line 253 of file Camera\&.cpp\&.
.SS "void Camera::dPos (const \fBvec4\fP &by)"

.PP
Moves the camera along the x, y, and z axes\&. \fBParameters:\fP
.RS 4
\fIby\fP A vec4 containing the X, Y, and Z axis displacements\&. The w component is ignored\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
Void\&. 
.RE
.PP

.PP
Definition at line 263 of file Camera\&.cpp\&.
.SS "void Camera::dX (const float &by, const bool &update = \fCtrue\fP)"

.PP
Moves the camera along the X axis\&. \fBParameters:\fP
.RS 4
\fIby\fP The float value of the X-axis displacement\&. 
.br
\fIupdate\fP A boolean indicating whether or not to update the shader\&. update defaults to true\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
void\&. 
.RE
.PP

.PP
Definition at line 202 of file Camera\&.cpp\&.
.SS "void Camera::dY (const float &by, const bool &update = \fCtrue\fP)"

.PP
Moves the camera along the Y axis\&. \fBParameters:\fP
.RS 4
\fIby\fP The float value of the Y-axis displacement\&. 
.br
\fIupdate\fP A boolean indicating whether or not to update the shader\&. update defaults to true\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
Void\&. 
.RE
.PP

.PP
Definition at line 214 of file Camera\&.cpp\&.
.SS "void Camera::dZ (const float &by, const bool &update = \fCtrue\fP)"

.PP
Moves the camera along the Z axis\&. \fBParameters:\fP
.RS 4
\fIby\fP The float value of the Z-axis displacement\&. 
.br
\fIupdate\fP A boolean indicating whether or not to update the shader\&. update defaults to true\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
Void\&. 
.RE
.PP

.PP
Definition at line 226 of file Camera\&.cpp\&.
.SS "void Camera::FOV (const float &in)"

.PP
FOV sets the current camera Field-of-view angle\&. This function will send the new perspective matrix to the shader\&. 
.PP
\fBParameters:\fP
.RS 4
\fIin\fP The new field of view angle\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
Void\&. 
.RE
.PP

.PP
Definition at line 592 of file Camera\&.cpp\&.
.SS "float Camera::FOV (void) const"

.PP
\fBFOV()\fP gets the current camera Field-of-view angle\&. \fBReturns:\fP
.RS 4
A float that is the y axis viewing angle\&. 
.RE
.PP

.PP
Definition at line 583 of file Camera\&.cpp\&.
.SS "void Camera::heave (const float &by)"

.PP
Adjusts the camera's Y coordinate relative to its current position\&. Positive values move the camera up, and negative values move the camera down\&. 
.PP
\fBParameters:\fP
.RS 4
\fIby\fP The float to adjust the Y coordinate by\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
Void\&. 
.RE
.PP

.PP
Definition at line 348 of file Camera\&.cpp\&.
.SS "void Camera::Idle (void)"

.PP
Idle moves the camera forward in whichever directions it is configured to move in\&. Call it in the glut Idle function\&. 
.PP
\fBReturns:\fP
.RS 4
Void\&. 
.RE
.PP

.PP
Definition at line 491 of file Camera\&.cpp\&.
.SS "void Camera::Move (const \fBCamera::Direction\fP &Dir)"

.PP
Move instructs the camera to begin moving in the specified direction\&. \fBParameters:\fP
.RS 4
\fIDir\fP The direction in which to move\&. Can be any direction in the enumerated type \fBCamera::Direction\fP\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
Void\&. 
.RE
.PP

.PP
Definition at line 471 of file Camera\&.cpp\&.
.SS "void Camera::pitch (const float &by, const bool &fixed = \fCfalse\fP)"

.PP
pitch adjusts the X axis rotation; up/down look\&. A positive value represents looking up, while a negative value represents looking down\&. 
.PP
\fBParameters:\fP
.RS 4
\fIby\fP A float, in degrees, to adjust the pitch by\&. 
.br
\fIfixed\fP Should this rotation be fixed about the origin? 
.RE
.PP
\fBReturns:\fP
.RS 4
Void\&. 
.RE
.PP

.PP
Definition at line 361 of file Camera\&.cpp\&.
.SS "void Camera::pos (const float &x, const float &y, const float &z, const bool &update = \fCtrue\fP)"

.PP
Sets the absolute position of the camera\&. \fBParameters:\fP
.RS 4
\fIx\fP The new X coordinate of the camera\&. 
.br
\fIy\fP The new Y coordinate of the camera\&. 
.br
\fIz\fP The new Z coordinate of the camera\&. 
.br
\fIupdate\fP Whether or not to update the shader with the new coordinates\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
Void\&. 
.RE
.PP

.PP
Definition at line 161 of file Camera\&.cpp\&.
.SS "void Camera::pos (const \fBvec3\fP &in, const bool &update = \fCtrue\fP)"

.PP
Sets the absolute position of the camera\&. \fBParameters:\fP
.RS 4
\fIin\fP A vec3 containing the x, y, and z coordinates to set the camera to\&. 
.br
\fIupdate\fP Whether or not to update the shader with the new coordinates\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
Void\&. 
.RE
.PP

.PP
Definition at line 190 of file Camera\&.cpp\&.
.SS "void Camera::pos (const \fBvec4\fP &in, const bool &update = \fCtrue\fP)"

.PP
Sets the absolute position of the camera\&. \fBParameters:\fP
.RS 4
\fIin\fP A vec4 containing the x, y, and z coordinates to set the camera to\&. The w coordinate is ignored\&. 
.br
\fIupdate\fP Whether or not to update the shader with the new coordinates\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
Void\&. 
.RE
.PP

.PP
Definition at line 179 of file Camera\&.cpp\&.
.SS "\fBvec4\fP Camera::pos (void) const"

.PP
\fBpos()\fP gets the current camera position in model coordinates\&. \fBReturns:\fP
.RS 4
A vec4 that represents the current camera coordinates\&. 
.RE
.PP

.PP
Definition at line 576 of file Camera\&.cpp\&.
.SS "void Camera::refreshPerspective (void)"

.PP
refreshPerspective re-generates the current view/perspective matrix of the camera\&. This function should be called after physical or virtual (viewport) screen resizes\&. 
.PP
\fBReturns:\fP
.RS 4
Void\&. 
.RE
.PP

.PP
Definition at line 617 of file Camera\&.cpp\&.
.SS "void Camera::roll (const float &by, const bool &fixed = \fCfalse\fP)"

.PP
roll adjusts the Z axis rotation; tilt or lean left/right\&. A positive value represents leaning right, while a negative value represents leaning left\&. 
.PP
\fBParameters:\fP
.RS 4
\fIby\fP A float, in degrees, to adjust the roll by\&. 
.br
\fIfixed\fP Should this rotation be fixed about the origin? 
.RE
.PP
\fBReturns:\fP
.RS 4
Void\&. 
.RE
.PP

.PP
Definition at line 400 of file Camera\&.cpp\&.
.SS "void Camera::Send (Object::UniformEnumwhich)\fC [virtual]\fP"

.PP
send will send a glsl variable to the shader\&. \fBParameters:\fP
.RS 4
\fIwhich\fP The parameter to send\&. Can be any from enum glsl_var\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
Void\&. 
.RE
.PP

.PP
Reimplemented from \fBObject\fP\&.
.PP
Definition at line 677 of file Camera\&.cpp\&.
.SS "void Camera::Stop (const \fBCamera::Direction\fP &Dir)"

.PP
Stop instructs the camera to stop moving in the specified direction\&. \fBParameters:\fP
.RS 4
\fIDir\fP The direction in which to stop moving\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
Void\&. 
.RE
.PP

.PP
Definition at line 481 of file Camera\&.cpp\&.
.SS "void Camera::surge (const float &by)"

.PP
Adjusts the camera's Z coordinate relative to its current position\&. Positive values move the camera forward, and negative values move the camera backward\&. Note that the camera uses model coordinates internally, so moving forward will increase the camera's Z position negatively\&. 
.PP
\fBParameters:\fP
.RS 4
\fIby\fP The float to adjust the Z coordinate by\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
Void\&. 
.RE
.PP

.PP
Definition at line 336 of file Camera\&.cpp\&.
.SS "void Camera::sway (const float &by)"

.PP
Adjusts the camera's X coordinate relative to its current position\&. Negative values move the camera left, and positive values move the camera right\&. 
.PP
\fBParameters:\fP
.RS 4
\fIby\fP The float to adjust the X coordinate by\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
Void\&. 
.RE
.PP

.PP
Definition at line 322 of file Camera\&.cpp\&.
.SS "void Camera::View (void)"

.PP
View will instruct OpenGL of the viewport we want, and then send all of our current matrices to the shader for rendering\&. \fBReturns:\fP
.RS 4
Void\&. 
.RE
.PP

.PP
Definition at line 733 of file Camera\&.cpp\&.
.SS "void Camera::viewport (size_t_X, size_t_Y, size_t_Width, size_t_Height)"

.PP
viewport instructs this camera what his expected drawing window will be\&. This allows the camera to generate his viewing matrices with the correct aspect ratio\&. 
.PP
\fBParameters:\fP
.RS 4
\fI_X\fP The X coordinate of the lower-left corner of our viewport\&. 
.br
\fI_Y\fP the Y coordinate of the lower-left corner of our viewport\&. 
.br
\fI_Width\fP The width of our viewport\&. 
.br
\fI_Height\fP the height of our viewport\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
Void\&. 
.RE
.PP

.PP
Definition at line 664 of file Camera\&.cpp\&.
.SS "void Camera::X (const float &in, const bool &update = \fCtrue\fP)"

.PP
Sets the X coordinate of the camera\&. \fBParameters:\fP
.RS 4
\fIin\fP The new X coordinate of the camera\&. 
.br
\fIupdate\fP Whether or not to update the shader with the new coordinates\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
Void\&. 
.RE
.PP

.PP
Definition at line 111 of file Camera\&.cpp\&.
.SS "float Camera::X (void) const"

.PP
\fBX()\fP returns the current position of the camera in model coordinates\&. \fBReturns:\fP
.RS 4
The current X coordinate of the camera in model coordinates\&. 
.RE
.PP

.PP
Definition at line 555 of file Camera\&.cpp\&.
.SS "void Camera::Y (const float &in, const bool &update = \fCtrue\fP)"

.PP
Sets the Y coordinate of the camera\&. \fBParameters:\fP
.RS 4
\fIin\fP The new Y coordinate of the camera\&. 
.br
\fIupdate\fP Whether or not to update the shader with the new coordinates\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
Void\&. 
.RE
.PP

.PP
Definition at line 127 of file Camera\&.cpp\&.
.SS "float Camera::Y (void) const"

.PP
\fBY()\fP returns the current position of the camera in model coordinates\&. \fBReturns:\fP
.RS 4
The current Y coordinate of the camera in model coordinates\&. 
.RE
.PP

.PP
Definition at line 562 of file Camera\&.cpp\&.
.SS "void Camera::yaw (const float &by, const bool &fixed = \fCfalse\fP)"

.PP
yaw adjusts the Y axis rotation; left/right look\&. A positive value represents looking right, while a negative value represents looking left\&. 
.PP
\fBParameters:\fP
.RS 4
\fIby\fP A float, in degrees, to adjust the yaw by\&. 
.br
\fIfixed\fP Should this rotation be fixed about the origin? 
.RE
.PP
\fBReturns:\fP
.RS 4
Void\&. 
.RE
.PP

.PP
Definition at line 381 of file Camera\&.cpp\&.
.SS "void Camera::Z (const float &in, const bool &update = \fCtrue\fP)"

.PP
Sets the Z coordinate of the camera\&. \fBParameters:\fP
.RS 4
\fIin\fP The new Z coordinate of the camera\&. 
.br
\fIupdate\fP Whether or not to update the shader with the new coordinates\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
Void\&. 
.RE
.PP

.PP
Definition at line 143 of file Camera\&.cpp\&.
.SS "float Camera::Z (void) const"

.PP
\fBZ()\fP returns the current position of the camera in model coordinates\&. \fBReturns:\fP
.RS 4
The current Z coordinate of the camera in model coordinates\&. 
.RE
.PP

.PP
Definition at line 569 of file Camera\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "GLfloat Camera::aspect\fC [private]\fP"

.PP
Current aspect ratio for certain perspectives\&. 
.PP
Definition at line 183 of file Camera\&.hpp\&.
.SS "\fBmat4\fP Camera::ctm\fC [private]\fP"

.PP
The 'Current \fBTransformation\fP Matrix' for this camera\&. May be P*R*T or T*R*P depending on the current POST/PRE mult configurations\&. 
.PP
Definition at line 159 of file Camera\&.hpp\&.
.SS "\fBview_type\fP Camera::currView\fC [private]\fP"

.PP
The current viewing mode type\&. 
.PP
Definition at line 162 of file Camera\&.hpp\&.
.SS "GLenum Object::draw_mode\fC [protected]\fP, \fC [inherited]\fP"

.PP
Drawing mode for this object\&. GL_TRIANGLES, GL_LINE_LOOP, etc\&. 
.PP
Definition at line 76 of file Object\&.hpp\&.
.SS "GLfloat Camera::fovy\fC [private]\fP"

.PP
Current field-of-view angle for perspective view\&. 
.PP
Definition at line 186 of file Camera\&.hpp\&.
.SS "GLfloat Camera::FrictionMagnitude\fC [private]\fP"

.PP
Friction\&. Should be less than MaxAccel\&. 
.PP
Definition at line 180 of file Camera\&.hpp\&.
.SS "std::vector< GLint > Object::handles\fC [inherited]\fP"

.PP
Handles to Uniforms on the shader\&. Private to allow derived classes to extend it as needed\&. 
.PP
Definition at line 63 of file Object\&.hpp\&.
.SS "bool Camera::Motion[Camera::Direction_End]\fC [private]\fP"

.PP
Booleans correlating to the different motion directions\&. 
.PP
Definition at line 195 of file Camera\&.hpp\&.
.SS "std::string Object::name\fC [protected]\fP, \fC [inherited]\fP"

.PP
name is used as an identifying handle for the object\&. 
.PP
Definition at line 67 of file Object\&.hpp\&.
.SS "\fBmat4\fP Camera::P\fC [private]\fP"

.PP
The current view matrix (usually perspective) for this camera\&. 
.PP
Definition at line 156 of file Camera\&.hpp\&.
.SS "\fBmat4\fP Camera::R\fC [private]\fP"

.PP
The current rotational matrix for this camera\&. 
.PP
Definition at line 154 of file Camera\&.hpp\&.
.SS "GLfloat Camera::speed\fC [private]\fP"

.PP
Current Speed of camera motion\&. 
.PP
Definition at line 165 of file Camera\&.hpp\&.
.SS "\fBmat4\fP Camera::T\fC [private]\fP"

.PP
The current translation matrix for this camera\&. 
.PP
Definition at line 152 of file Camera\&.hpp\&.
.SS "GLuint Object::vao\fC [protected]\fP, \fC [inherited]\fP"

.PP
Vertex Array \fBObject\fP handle identifying our buffers/object\&. 
.PP
Definition at line 70 of file Object\&.hpp\&.
.SS "\fBvec3\fP Camera::velocity\fC [private]\fP"

.PP
Current Velocity of camera motion\&. 
.PP
Definition at line 168 of file Camera\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for OpenGL Flythrough from the source code\&.
