.TH "CBalanceBoard" 3 "Sun Dec 9 2012" "Version 9001" "OpenGL Flythrough" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CBalanceBoard \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCBalanceBoard\fP (struct \fBexpansion_t\fP *BBPtr)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBCWeightSensor\fP \fBWeightSensor\fP"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "struct \fBbalance_board_t\fP * \fBmpBBPtr\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 362 of file wiicpp\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for OpenGL Flythrough from the source code\&.
