.TH "CButtonBase" 3 "Wed Dec 5 2012" "Version 001" "OpenGL Flythrough" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CButtonBase \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBCButtons\fP, \fBCClassicButtons\fP, \fBCGH3Buttons\fP, and \fBCNunchukButtons\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCButtonBase\fP (void *ButtonsPtr, void *ButtonsHeldPtr, void *ButtonsReleasedPtr)"
.br
.ti -1c
.RI "int \fBisPressed\fP (int Button)"
.br
.ti -1c
.RI "int \fBisHeld\fP (int Button)"
.br
.ti -1c
.RI "int \fBisReleased\fP (int Button)"
.br
.ti -1c
.RI "int \fBisJustPressed\fP (int Button)"
.br
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "virtual short \fBCast\fP (void *Ptr)"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "void * \fBmpBtnsPtr\fP"
.br
.ti -1c
.RI "void * \fBmpBtnsHeldPtr\fP"
.br
.ti -1c
.RI "void * \fBmpBtnsReleasedPtr\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 43 of file wiicpp\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for OpenGL Flythrough from the source code\&.
