.TH "CClassic" 3 "Mon Dec 3 2012" "Version 001" "OpenGL Flythrough" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CClassic \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCClassic\fP (struct \fBexpansion_t\fP *ExpPtr)"
.br
.ti -1c
.RI "float \fBGetLShoulderButton\fP ()"
.br
.ti -1c
.RI "float \fBGetRShoulderButton\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBCClassicButtons\fP \fBButtons\fP"
.br
.ti -1c
.RI "\fBCJoystick\fP \fBLeftJoystick\fP"
.br
.ti -1c
.RI "\fBCJoystick\fP \fBRightJoystick\fP"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "struct \fBclassic_ctrl_t\fP * \fBmpClassicPtr\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 318 of file wiicpp\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for OpenGL Flythrough from the source code\&.
