.TH "CClassicButtons" 3 "Sat Dec 8 2012" "Version 001" "OpenGL Flythrough" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CClassicButtons \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCButtonBase\fP\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBButtonDefs\fP { \fBBUTTON_X\fP =  CLASSIC_CTRL_BUTTON_X, \fBBUTTON_Y\fP =  CLASSIC_CTRL_BUTTON_Y, \fBBUTTON_B\fP =  CLASSIC_CTRL_BUTTON_B, \fBBUTTON_A\fP =  CLASSIC_CTRL_BUTTON_A, \fBBUTTON_MINUS\fP =  CLASSIC_CTRL_BUTTON_MINUS, \fBBUTTON_HOME\fP =  CLASSIC_CTRL_BUTTON_HOME, \fBBUTTON_LEFT\fP =  CLASSIC_CTRL_BUTTON_LEFT, \fBBUTTON_RIGHT\fP =  CLASSIC_CTRL_BUTTON_RIGHT, \fBBUTTON_DOWN\fP =  CLASSIC_CTRL_BUTTON_DOWN, \fBBUTTON_UP\fP =  CLASSIC_CTRL_BUTTON_UP, \fBBUTTON_PLUS\fP =  CLASSIC_CTRL_BUTTON_PLUS, \fBBUTTON_ZR\fP =  CLASSIC_CTRL_BUTTON_ZR, \fBBUTTON_ZL\fP =  CLASSIC_CTRL_BUTTON_ZL, \fBBUTTON_FULL_R\fP =  CLASSIC_CTRL_BUTTON_FULL_R, \fBBUTTON_FULL_L\fP =  CLASSIC_CTRL_BUTTON_FULL_L, \fBBUTTON_ALL\fP =  CLASSIC_CTRL_BUTTON_ALL }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCClassicButtons\fP (void *ButtonsPtr, void *ButtonsHeldPtr, void *ButtonsReleasedPtr)"
.br
.ti -1c
.RI "int \fBisPressed\fP (int Button)"
.br
.ti -1c
.RI "int \fBisHeld\fP (int Button)"
.br
.ti -1c
.RI "int \fBisReleased\fP (int Button)"
.br
.ti -1c
.RI "int \fBisJustPressed\fP (int Button)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 100 of file wiicpp\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for OpenGL Flythrough from the source code\&.
