.TH "CGuitarHero3" 3 "Mon Dec 3 2012" "Version 001" "OpenGL Flythrough" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CGuitarHero3 \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCGuitarHero3\fP (struct \fBexpansion_t\fP *ExpPtr)"
.br
.ti -1c
.RI "float \fBGetWhammyBar\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBCGH3Buttons\fP \fBButtons\fP"
.br
.ti -1c
.RI "\fBCJoystick\fP \fBJoystick\fP"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "struct \fBguitar_hero_3_t\fP * \fBmpGH3Ptr\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 334 of file wiicpp\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for OpenGL Flythrough from the source code\&.
