.TH "CIR" 3 "Sat Dec 8 2012" "Version 001" "OpenGL Flythrough" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CIR \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBBarPositions\fP { \fBBAR_ABOVE\fP =  WIIC_IR_ABOVE, \fBBAR_BELOW\fP =  WIIC_IR_BELOW }"
.br
.ti -1c
.RI "enum \fBAspectRatioSelections\fP { \fBASPECT_4_3\fP =  WIIC_ASPECT_4_3, \fBASPECT_16_9\fP =  WIIC_ASPECT_16_9 }"
.br
.ti -1c
.RI "enum \fBOnOffSelection\fP { \fBOFF\fP =  0, \fBON\fP =  1 }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCIR\fP (struct \fBwiimote_t\fP *wmPtr)"
.br
.ti -1c
.RI "void \fBSetMode\fP (OnOffSelection State)"
.br
.ti -1c
.RI "void \fBSetVres\fP (unsigned int x, unsigned int y)"
.br
.ti -1c
.RI "BarPositions \fBGetBarPositionSetting\fP ()"
.br
.ti -1c
.RI "void \fBSetBarPosition\fP (BarPositions PositionSelection)"
.br
.ti -1c
.RI "AspectRatioSelections \fBGetAspectRatioSetting\fP ()"
.br
.ti -1c
.RI "void \fBSetAspectRatio\fP (AspectRatioSelections AspectRatioSelection)"
.br
.ti -1c
.RI "void \fBSetSensitivity\fP (int Level)"
.br
.ti -1c
.RI "int \fBGetSensitivity\fP ()"
.br
.ti -1c
.RI "int \fBGetNumDots\fP ()"
.br
.ti -1c
.RI "std::vector< \fBCIRDot\fP > & \fBGetDots\fP ()"
.br
.ti -1c
.RI "void \fBGetOffset\fP (int &X, int &Y)"
.br
.ti -1c
.RI "int \fBGetState\fP ()"
.br
.ti -1c
.RI "void \fBGetCursorPositionAbsolute\fP (int &X, int &Y)"
.br
.ti -1c
.RI "void \fBGetCursorPosition\fP (int &X, int &Y)"
.br
.ti -1c
.RI "float \fBGetPixelDistance\fP ()"
.br
.ti -1c
.RI "float \fBGetDistance\fP ()"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "struct \fBwiimote_t\fP * \fBmpWiimotePtr\fP"
.br
.ti -1c
.RI "std::vector< \fBCIRDot\fP > \fBmpIRDotsVector\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 255 of file wiicpp\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for OpenGL Flythrough from the source code\&.
