.TH "CJoystick" 3 "Mon Dec 3 2012" "Version 001" "OpenGL Flythrough" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CJoystick \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCJoystick\fP (struct \fBjoystick_t\fP *JSPtr)"
.br
.ti -1c
.RI "void \fBGetMaxCal\fP (int &X, int &Y)"
.br
.ti -1c
.RI "void \fBSetMaxCal\fP (int X, int Y)"
.br
.ti -1c
.RI "void \fBGetMinCal\fP (int &X, int &Y)"
.br
.ti -1c
.RI "void \fBSetMinCal\fP (int X, int Y)"
.br
.ti -1c
.RI "void \fBGetCenterCal\fP (int &X, int &Y)"
.br
.ti -1c
.RI "void \fBSetCenterCal\fP (int X, int Y)"
.br
.ti -1c
.RI "void \fBGetPosition\fP (float &Angle, float &Magnitude)"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "struct \fBjoystick_t\fP * \fBmpJoystickPtr\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 146 of file wiicpp\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for OpenGL Flythrough from the source code\&.
