.TH "CNunchukButtons" 3 "Sat Dec 1 2012" "Version 001" "OpenGL Flythrough" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CNunchukButtons \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCButtonBase\fP\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBButtonDefs\fP { \fBBUTTON_Z\fP =  NUNCHUK_BUTTON_Z, \fBBUTTON_C\fP =  NUNCHUK_BUTTON_C, \fBBUTTON_ALL\fP =  NUNCHUK_BUTTON_ALL }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCNunchukButtons\fP (void *ButtonsPtr, void *ButtonsHeldPtr, void *ButtonsReleasedPtr)"
.br
.ti -1c
.RI "int \fBisPressed\fP (int Button)"
.br
.ti -1c
.RI "int \fBisHeld\fP (int Button)"
.br
.ti -1c
.RI "int \fBisReleased\fP (int Button)"
.br
.ti -1c
.RI "int \fBisJustPressed\fP (int Button)"
.br
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "short \fBCast\fP (void *Ptr)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 84 of file wiicpp\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for OpenGL Flythrough from the source code\&.
