.TH "CNunchuk" 3 "Sat Dec 1 2012" "Version 001" "OpenGL Flythrough" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CNunchuk \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCNunchuk\fP (struct \fBexpansion_t\fP *ExpPtr)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBCNunchukButtons\fP \fBButtons\fP"
.br
.ti -1c
.RI "\fBCJoystick\fP \fBJoystick\fP"
.br
.ti -1c
.RI "\fBCAccelerometer\fP \fBAccelerometer\fP"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "struct \fBnunchuk_t\fP * \fBmpNunchukPtr\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 305 of file wiicpp\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for OpenGL Flythrough from the source code\&.
