.TH "CWiimote" 3 "Sun Dec 2 2012" "Version 001" "OpenGL Flythrough" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CWiimote \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBLEDS\fP { \fBLED_NONE\fP =  WIIMOTE_LED_NONE, \fBLED_1\fP =  WIIMOTE_LED_1, \fBLED_2\fP =  WIIMOTE_LED_2, \fBLED_3\fP =  WIIMOTE_LED_3, \fBLED_4\fP =  WIIMOTE_LED_4 }"
.br
.ti -1c
.RI "enum \fBFlags\fP { \fBFLAG_SMOOTHING\fP =  WIIC_SMOOTHING, \fBFLAG_CONTINUOUS\fP =  WIIC_CONTINUOUS, \fBFLAG_ORIENT_THRESH\fP =  WIIC_ORIENT_THRESH, \fBFLAG_INIT_FLAGS\fP =  WIIC_INIT_FLAGS }"
.br
.ti -1c
.RI "enum \fBEventTypes\fP { \fBEVENT_NONE\fP =  WIIC_NONE, \fBEVENT_EVENT\fP =  WIIC_EVENT, \fBEVENT_STATUS\fP =  WIIC_STATUS, \fBEVENT_CONNECT\fP =  WIIC_CONNECT, \fBEVENT_DISCONNECT\fP =  WIIC_DISCONNECT, \fBEVENT_UNEXPECTED_DISCONNECT\fP =  WIIC_UNEXPECTED_DISCONNECT, \fBEVENT_READ_DATA\fP =  WIIC_READ_DATA, \fBEVENT_NUNCHUK_INSERTED\fP =  WIIC_NUNCHUK_INSERTED, \fBEVENT_NUNCHUK_REMOVED\fP =  WIIC_NUNCHUK_REMOVED, \fBEVENT_CLASSIC_CTRL_INSERTED\fP =  WIIC_CLASSIC_CTRL_INSERTED, \fBEVENT_CLASSIC_CTRL_REMOVED\fP =  WIIC_CLASSIC_CTRL_REMOVED, \fBEVENT_GUITAR_HERO_3_CTRL_INSERTED\fP =  WIIC_GUITAR_HERO_3_CTRL_INSERTED, \fBEVENT_GUITAR_HERO_3_CTRL_REMOVED\fP =  WIIC_GUITAR_HERO_3_CTRL_REMOVED, \fBEVENT_MOTION_PLUS_INSERTED\fP =  WIIC_MOTION_PLUS_INSERTED, \fBEVENT_MOTION_PLUS_REMOVED\fP =  WIIC_MOTION_PLUS_REMOVED, \fBEVENT_BALANCE_BOARD_INSERTED\fP =  WIIC_BALANCE_BOARD_INSERTED, \fBEVENT_BALANCE_BOARD_REMOVED\fP =  WIIC_BALANCE_BOARD_REMOVED }"
.br
.ti -1c
.RI "enum \fBOnOffSelection\fP { \fBOFF\fP =  0, \fBON\fP =  1 }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCWiimote\fP (struct \fBwiimote_t\fP *wmPtr)"
.br
.ti -1c
.RI "\fBCWiimote\fP (const \fBCWiimote\fP &copyin)"
.br
.ti -1c
.RI "void \fBDisconnected\fP ()"
.br
.ti -1c
.RI "void \fBSetRumbleMode\fP (OnOffSelection State)"
.br
.ti -1c
.RI "void \fBToggleRumble\fP ()"
.br
.ti -1c
.RI "bool \fBisRumbleEnabled\fP ()"
.br
.ti -1c
.RI "int \fBGetLEDs\fP ()"
.br
.ti -1c
.RI "void \fBSetLEDs\fP (int LEDs)"
.br
.ti -1c
.RI "float \fBGetBatteryLevel\fP ()"
.br
.ti -1c
.RI "int \fBGetHandshakeState\fP ()"
.br
.ti -1c
.RI "EventTypes \fBGetEvent\fP ()"
.br
.ti -1c
.RI "const unsigned char * \fBGetEventBuffer\fP ()"
.br
.ti -1c
.RI "void \fBSetSmoothing\fP (bool Smooth)"
.br
.ti -1c
.RI "void \fBSetMotionSensingMode\fP (OnOffSelection State)"
.br
.ti -1c
.RI "void \fBEnableMotionPlus\fP (OnOffSelection State)"
.br
.ti -1c
.RI "void \fBLogStart\fP (int type=WIIC_LOG_NONE, const string &file='')"
.br
.ti -1c
.RI "void \fBLogStop\fP ()"
.br
.ti -1c
.RI "void \fBLog\fP ()"
.br
.ti -1c
.RI "struct timeval \fBGetTimestamp\fP () const "
.br
.ti -1c
.RI "void \fBEnableSpeaker\fP (OnOffSelection State)"
.br
.ti -1c
.RI "void \fBMuteSpeaker\fP (OnOffSelection State)"
.br
.ti -1c
.RI "void \fBPlaySound\fP ()"
.br
.ti -1c
.RI "void \fBReadData\fP (unsigned char *Buffer, unsigned int Offset, unsigned int Length)"
.br
.ti -1c
.RI "void \fBWriteData\fP (unsigned int Address, unsigned char *Data, unsigned int Length)"
.br
.ti -1c
.RI "void \fBUpdateStatus\fP ()"
.br
.ti -1c
.RI "int \fBGetID\fP ()"
.br
.ti -1c
.RI "const char * \fBGetAddress\fP ()"
.br
.ti -1c
.RI "int \fBGetState\fP ()"
.br
.ti -1c
.RI "int \fBGetFlags\fP ()"
.br
.ti -1c
.RI "int \fBSetFlags\fP (int Enable, int Disable)"
.br
.ti -1c
.RI "void \fBResync\fP ()"
.br
.ti -1c
.RI "void \fBDisconnect\fP ()"
.br
.ti -1c
.RI "int \fBisUsingACC\fP ()"
.br
.ti -1c
.RI "int \fBisUsingEXP\fP ()"
.br
.ti -1c
.RI "int \fBisUsingIR\fP ()"
.br
.ti -1c
.RI "int \fBisUsingSpeaker\fP ()"
.br
.ti -1c
.RI "int \fBisSpeakerMuted\fP ()"
.br
.ti -1c
.RI "int \fBisUsingMotionPlus\fP ()"
.br
.ti -1c
.RI "int \fBisLEDSet\fP (int LEDNum)"
.br
.ti -1c
.RI "bool \fBisLogEnabled\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBCIR\fP \fBIR\fP"
.br
.ti -1c
.RI "\fBCButtons\fP \fBButtons\fP"
.br
.ti -1c
.RI "\fBCAccelerometer\fP \fBAccelerometer\fP"
.br
.ti -1c
.RI "\fBCExpansionDevice\fP \fBExpansionDevice\fP"
.br
.ti -1c
.RI "struct \fBwiimote_t\fP * \fBmpWiimotePtr\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static const int \fBEVENT_BUFFER_LENGTH\fP = MAX_PAYLOAD"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "int \fBmpTempInt\fP"
.br
.ti -1c
.RI "float \fBmpTempFloat\fP"
.br
.ti -1c
.RI "\fBLogger\fP \fBlogger\fP"
.br
.ti -1c
.RI "int \fBlogType\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 400 of file wiicpp\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for OpenGL Flythrough from the source code\&.
