.TH "guitar_hero_3_t" 3 "Mon Dec 3 2012" "Version 001" "OpenGL Flythrough" \" -*- nroff -*-
.ad l
.nh
.SH NAME
guitar_hero_3_t \- 
.PP
Guitar Hero 3 expansion device\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <wiic_structs\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "short \fBbtns\fP"
.br
.RI "\fIwhat buttons have just been pressed \fP"
.ti -1c
.RI "short \fBbtns_held\fP"
.br
.RI "\fIwhat buttons are being held down \fP"
.ti -1c
.RI "short \fBbtns_released\fP"
.br
.RI "\fIwhat buttons were just released this \fP"
.ti -1c
.RI "float \fBwhammy_bar\fP"
.br
.RI "\fIwhammy bar (range 0-1) \fP"
.ti -1c
.RI "struct \fBjoystick_t\fP \fBjs\fP"
.br
.RI "\fIjoystick calibration \fP"
.in -1c
.SH "Detailed Description"
.PP 
Guitar Hero 3 expansion device\&. 
.PP
Definition at line 308 of file wiic_structs\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for OpenGL Flythrough from the source code\&.
