.TH "io_mac.h" 3 "Wed Dec 5 2012" "Version 001" "OpenGL Flythrough" \" -*- nroff -*-
.ad l
.nh
.SH NAME
io_mac.h \- 
.PP
I/O header file for MacOS\&.  

.SH SYNOPSIS
.br
.PP
\fC#import <stdio\&.h>\fP
.br
\fC#import <stdlib\&.h>\fP
.br
\fC#import <unistd\&.h>\fP
.br
\fC#import <arpa/inet\&.h>\fP
.br
\fC#import <IOBluetooth/IOBluetoothUtilities\&.h>\fP
.br
\fC#import <IOBluetooth/objc/IOBluetoothDevice\&.h>\fP
.br
\fC#import <IOBluetooth/objc/IOBluetoothHostController\&.h>\fP
.br
\fC#import <IOBluetooth/objc/IOBluetoothDeviceInquiry\&.h>\fP
.br
\fC#import <IOBluetooth/objc/IOBluetoothL2CAPChannel\&.h>\fP
.br
\fC#import 'wiic_internal\&.h'\fP
.br
\fC#import 'io\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBWiiSearch\fP"
.br
.ti -1c
.RI "class \fBWiiConnect\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
I/O header file for MacOS\&. 


.PP
Definition in file \fBio_mac\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for OpenGL Flythrough from the source code\&.
