.TH "ir_dot_t" 3 "Sun Dec 9 2012" "Version 9001" "OpenGL Flythrough" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ir_dot_t \- 
.PP
A single IR source\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <wiic_structs\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBbyte\fP \fBvisible\fP"
.br
.RI "\fIif the IR source is visible \fP"
.ti -1c
.RI "unsigned int \fBx\fP"
.br
.RI "\fIinterpolated X coordinate \fP"
.ti -1c
.RI "unsigned int \fBy\fP"
.br
.RI "\fIinterpolated Y coordinate \fP"
.ti -1c
.RI "short \fBrx\fP"
.br
.RI "\fIraw X coordinate (0-1023) \fP"
.ti -1c
.RI "short \fBry\fP"
.br
.RI "\fIraw Y coordinate (0-767) \fP"
.ti -1c
.RI "\fBbyte\fP \fBorder\fP"
.br
.RI "\fIincreasing order by x-axis value \fP"
.ti -1c
.RI "\fBbyte\fP \fBsize\fP"
.br
.RI "\fIsize of the IR dot (0-15) \fP"
.in -1c
.SH "Detailed Description"
.PP 
A single IR source\&. 
.PP
Definition at line 195 of file wiic_structs\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for OpenGL Flythrough from the source code\&.
