.TH "joystick_t" 3 "Sat Dec 8 2012" "Version 001" "OpenGL Flythrough" \" -*- nroff -*-
.ad l
.nh
.SH NAME
joystick_t \- 
.PP
Joystick calibration structure\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <wiic_structs\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "struct \fBvec2b_t\fP \fBmax\fP"
.br
.RI "\fImaximum joystick values \fP"
.ti -1c
.RI "struct \fBvec2b_t\fP \fBmin\fP"
.br
.RI "\fIminimum joystick values \fP"
.ti -1c
.RI "struct \fBvec2b_t\fP \fBcenter\fP"
.br
.RI "\fIcenter joystick values \fP"
.ti -1c
.RI "float \fBang\fP"
.br
.RI "\fIangle the joystick is being held \fP"
.ti -1c
.RI "float \fBmag\fP"
.br
.RI "\fImagnitude of the joystick (range 0-1) \fP"
.in -1c
.SH "Detailed Description"
.PP 
Joystick calibration structure\&. 

The angle \fIang\fP is relative to the positive y-axis into quadrant I and ranges from 0 to 360 degrees\&. So if the joystick is held straight upwards then angle is 0 degrees\&. If it is held to the right it is 90, down is 180, and left is 270\&.
.PP
The magnitude \fImag\fP is the distance from the center to where the joystick is being held\&. The magnitude ranges from 0 to 1\&. If the joystick is only slightly tilted from the center the magnitude will be low, but if it is closer to the outter edge the value will be higher\&. 
.PP
Definition at line 252 of file wiic_structs\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for OpenGL Flythrough from the source code\&.
