.TH "LightSource" 3 "Tue Dec 18 2012" "Version 9001" "OpenGL Flythrough" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LightSource \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBLightSource\fP (const \fBpoint4\fP &)"
.br
.ti -1c
.RI "\fBLightSource\fP (const \fBpoint4\fP &, const \fBcolor4\fP &)"
.br
.ti -1c
.RI "\fBLightSource\fP (const \fBpoint4\fP &, const \fBcolor4\fP &, const \fBcolor4\fP &, const \fBcolor4\fP &)"
.br
.ti -1c
.RI "\fBLightSource\fP (const \fBpoint4\fP &, const \fBvec4\fP &, const \fBcolor4\fP &, const \fBcolor4\fP &, const \fBcolor4\fP &)"
.br
.ti -1c
.RI "\fBLightSource\fP (const \fBLightSource\fP &orig)"
.br
.ti -1c
.RI "void \fBSetLight_specular\fP (\fBcolor4\fP &light_specular)"
.br
.ti -1c
.RI "\fBcolor4\fP \fBGetLight_specular\fP () const "
.br
.ti -1c
.RI "void \fBSetLight_diffuse\fP (\fBcolor4\fP &light_diffuse)"
.br
.ti -1c
.RI "\fBcolor4\fP \fBGetLight_diffuse\fP () const "
.br
.ti -1c
.RI "void \fBSetLight_ambient\fP (\fBcolor4\fP &light_ambient)"
.br
.ti -1c
.RI "\fBcolor4\fP \fBGetLight_ambient\fP () const "
.br
.ti -1c
.RI "void \fBSetLight_color\fP (\fBcolor4\fP &light_color)"
.br
.ti -1c
.RI "\fBcolor4\fP \fBGetLight_color\fP () const "
.br
.ti -1c
.RI "void \fBSetDirection\fP (\fBvec4\fP &direction)"
.br
.ti -1c
.RI "\fBvec4\fP \fBGetDirection\fP () const "
.br
.ti -1c
.RI "void \fBSetPosition\fP (\fBpoint4\fP &z)"
.br
.ti -1c
.RI "\fBpoint4\fP \fBGetPosition\fP () const "
.br
.ti -1c
.RI "bool \fBGetComplexSwitch\fP () const "
.br
.ti -1c
.RI "void \fBDoEvents\fP (void)"
.br
.ti -1c
.RI "void \fBsetEffect\fP (int)"
.br
.in -1c
.SS "Private Types"

.in +1c
.ti -1c
.RI "enum \fBlight_effect\fP { \fBOFF\fP = 0, \fBON\fP, \fBBLINK\fP, \fBSTROBE\fP, \fBPULSE\fP }"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fBpoint4\fP \fBposition\fP"
.br
.ti -1c
.RI "\fBvec4\fP \fBdirection\fP"
.br
.ti -1c
.RI "\fBcolor4\fP \fBlight_ambient\fP"
.br
.ti -1c
.RI "\fBcolor4\fP \fBlight_diffuse\fP"
.br
.ti -1c
.RI "\fBcolor4\fP \fBlight_specular\fP"
.br
.ti -1c
.RI "\fBcolor4\fP \fBlight_color\fP"
.br
.ti -1c
.RI "bool \fBcomplexSwitch\fP"
.br
.ti -1c
.RI "light_effect \fBeffect\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 23 of file LightSource\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for OpenGL Flythrough from the source code\&.
