.TH "Lights" 3 "Sun Dec 2 2012" "Version 001" "OpenGL Flythrough" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Lights \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBremoveLightSource\fP ()"
.br
.ti -1c
.RI "void \fBaddLightSource\fP ()"
.br
.ti -1c
.RI "void \fBinit_lights\fP (GLuint program)"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "vector< \fBLightSource\fP > \fBtheLights\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 74 of file LightSource\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for OpenGL Flythrough from the source code\&.
