.TH "MLAlg" 3 "Sat Dec 1 2012" "Version 001" "OpenGL Flythrough" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MLAlg \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBtype\fP { \fBKNN\fP, \fBBayes\fP, \fBSVM\fP, \fBDT\fP, \fBANN\fP, \fBBoost\fP, \fBRT\fP, \fBNONE\fP, \fBNUMTYPES\fP, \fBKNN\fP, \fBBayes\fP, \fBSVM\fP, \fBDT\fP, \fBANN\fP, \fBBoost\fP, \fBRT\fP, \fBNONE\fP, \fBNUMTYPES\fP }"
.br
.ti -1c
.RI "enum \fBtype\fP { \fBKNN\fP, \fBBayes\fP, \fBSVM\fP, \fBDT\fP, \fBANN\fP, \fBBoost\fP, \fBRT\fP, \fBNONE\fP, \fBNUMTYPES\fP, \fBKNN\fP, \fBBayes\fP, \fBSVM\fP, \fBDT\fP, \fBANN\fP, \fBBoost\fP, \fBRT\fP, \fBNONE\fP, \fBNUMTYPES\fP }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMLAlg\fP (type t=KNN)"
.br
.ti -1c
.RI "void \fBsetType\fP (type t)"
.br
.ti -1c
.RI "void \fBsetType\fP (const string &st)"
.br
.ti -1c
.RI "string \fBgetType\fP ()"
.br
.ti -1c
.RI "void \fBsetCategoryNames\fP (const vector< string > &names)"
.br
.ti -1c
.RI "string \fBcategoryName\fP (int i)"
.br
.ti -1c
.RI "void \fBtrain\fP (const CvMat *trainIn, const CvMat *trainOut)"
.br
.ti -1c
.RI "void \fBvalidate\fP (const CvMat *validateIn, const CvMat *validateOut)"
.br
.ti -1c
.RI "void \fBrecognize\fP (const CvMat *recognizeIn, CvMat *recognizeOut)"
.br
.ti -1c
.RI "void \fBsave\fP (const char *filename) const "
.br
.ti -1c
.RI "void \fBload\fP (const char *filename)"
.br
.ti -1c
.RI "\fBMLAlg\fP (type t=KNN)"
.br
.ti -1c
.RI "void \fBsetType\fP (type t)"
.br
.ti -1c
.RI "void \fBsetType\fP (const string &st)"
.br
.ti -1c
.RI "string \fBgetType\fP ()"
.br
.ti -1c
.RI "void \fBsetCategoryNames\fP (const vector< string > &names)"
.br
.ti -1c
.RI "string \fBcategoryName\fP (int i)"
.br
.ti -1c
.RI "void \fBtrain\fP (const CvMat *trainIn, const CvMat *trainOut)"
.br
.ti -1c
.RI "void \fBvalidate\fP (const CvMat *validateIn, const CvMat *validateOut)"
.br
.ti -1c
.RI "void \fBrecognize\fP (const CvMat *recognizeIn, CvMat *recognizeOut)"
.br
.ti -1c
.RI "void \fBsave\fP (const char *filename) const "
.br
.ti -1c
.RI "void \fBload\fP (const char *filename)"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "CvKNearest \fBknn\fP"
.br
.ti -1c
.RI "CvNormalBayesClassifier \fBbayes\fP"
.br
.ti -1c
.RI "CvSVM \fBsvm\fP"
.br
.ti -1c
.RI "CvSVMParams \fBsvmparams\fP"
.br
.ti -1c
.RI "CvDTree \fBdt\fP"
.br
.ti -1c
.RI "CvDTreeParams \fBdtparams\fP"
.br
.ti -1c
.RI "CvRTrees \fBrt\fP"
.br
.ti -1c
.RI "CvRTParams \fBrtparams\fP"
.br
.ti -1c
.RI "CvBoost \fBboost\fP"
.br
.ti -1c
.RI "CvBoostParams \fBboostparams\fP"
.br
.ti -1c
.RI "CvANN_MLP \fBann\fP"
.br
.ti -1c
.RI "CvANN_MLP_TrainParams \fBannparams\fP"
.br
.ti -1c
.RI "int \fBK\fP"
.br
.ti -1c
.RI "type \fBtp\fP"
.br
.ti -1c
.RI "vector< string > \fBcategoryNames\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 8 of file wiic_r90/src/ml/MLAlg\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for OpenGL Flythrough from the source code\&.
