.TH "motionplus.h" 3 "Sun Dec 2 2012" "Version 001" "OpenGL Flythrough" \" -*- nroff -*-
.ad l
.nh
.SH NAME
motionplus.h \- 
.PP
Motion Plus expansion device\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'wiic_internal\&.h'\fP
.br
\fC#include <math\&.h>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBMP_SMOOTH_ALPHA\fP   0\&.65f"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmotion_plus_handshake\fP (struct \fBwiimote_t\fP *wm, \fBbyte\fP *data, unsigned short len)"
.br
.RI "\fIHandle the handshake from the Motion Plus\&. \fP"
.ti -1c
.RI "void \fBmotion_plus_disconnected\fP (struct \fBmotion_plus_t\fP *mp)"
.br
.RI "\fINotification of Motion Plus disconnection\&. \fP"
.ti -1c
.RI "void \fBmotion_plus_event\fP (struct \fBmotion_plus_t\fP *mp, \fBbyte\fP *msg)"
.br
.RI "\fIHandle Motion Plus event\&. \fP"
.ti -1c
.RI "void \fBwiic_set_mp_threshold\fP (struct \fBwiimote_t\fP *wm, int threshold)"
.br
.RI "\fISet the gyroscope event threshold\&. \fP"
.ti -1c
.RI "void \fBwiic_set_mp_smooth\fP (struct \fBwiimote_t\fP *wm, int status, float alpha)"
.br
.RI "\fIEnable the gyroscope smoothing (through an exponential moving average) \fP"
.ti -1c
.RI "void \fBmotion_plus_apply_smoothing\fP (struct \fBmotion_plus_t\fP *mp)"
.br
.RI "\fIApply smoothing to the Motion Plus gyroscopes\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Motion Plus expansion device\&. 


.PP
Definition in file \fBmotionplus\&.h\fP\&.
.SH "Function Documentation"
.PP 
.SS "void motion_plus_apply_smoothing (struct \fBmotion_plus_t\fP *mp)"

.PP
Apply smoothing to the Motion Plus gyroscopes\&. \fBParameters:\fP
.RS 4
\fImp\fP Pointer to a \fBmotion_plus_t\fP structure\&. 
.RE
.PP

.PP
Definition at line 123 of file motionplus\&.c\&.
.SS "void motion_plus_disconnected (struct \fBmotion_plus_t\fP *mp)"

.PP
Notification of Motion Plus disconnection\&. \fBParameters:\fP
.RS 4
\fImp\fP A pointer to a \fBmotion_plus_t\fP structure\&. 
.RE
.PP

.PP
Definition at line 250 of file motionplus\&.c\&.
.SS "void motion_plus_event (struct \fBmotion_plus_t\fP *mp, \fBbyte\fP *msg)"

.PP
Handle Motion Plus event\&. \fBParameters:\fP
.RS 4
\fImp\fP A pointer to a motionplus_t structure\&. 
.br
\fImsg\fP The message specified in the event packet\&. 
.RE
.PP

.PP
Definition at line 89 of file motionplus\&.c\&.
.SS "int motion_plus_handshake (struct \fBwiimote_t\fP *wm, \fBbyte\fP *data, unsigned shortlen)"

.PP
Handle the handshake from the Motion Plus\&. \fBParameters:\fP
.RS 4
\fIwm\fP A pointer to a \fBwiimote_t\fP structure\&. 
.br
\fIdata\fP The data that should contain the Motion Plus ID to check\&. 
.br
\fIlen\fP The length of the data block, in bytes\&.
.RE
.PP
\fBReturns:\fP
.RS 4
Returns 1 if handshake was successful, 0 if not\&. 
.RE
.PP

.PP
Definition at line 141 of file motionplus\&.c\&.
.SS "void wiic_set_mp_smooth (struct \fBwiimote_t\fP *wm, intstatus, floatalpha)"

.PP
Enable the gyroscope smoothing (through an exponential moving average) \fBParameters:\fP
.RS 4
\fIwm\fP Pointer to a \fBwiimote_t\fP structure\&. 
.br
\fIstatus\fP 1 to enable - 0 to disable 
.br
\fIalpha\fP Alpha smoothness parameter (between 0\&.0 and 1\&.0) 
.RE
.PP

.PP
Definition at line 275 of file motionplus\&.c\&.
.SS "void wiic_set_mp_threshold (struct \fBwiimote_t\fP *wm, intthreshold)"

.PP
Set the gyroscope event threshold\&. \fBParameters:\fP
.RS 4
\fIwm\fP Pointer to a \fBwiimote_t\fP structure\&. 
.br
\fIthreshold\fP The decimal place that should be considered a significant change\&. 
.RE
.PP

.PP
Definition at line 262 of file motionplus\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for OpenGL Flythrough from the source code\&.
