.TH "nunchuk_t" 3 "Sat Dec 1 2012" "Version 001" "OpenGL Flythrough" \" -*- nroff -*-
.ad l
.nh
.SH NAME
nunchuk_t \- 
.PP
Nunchuk expansion device\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <wiic_structs\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "struct \fBaccel_t\fP \fBaccel_calib\fP"
.br
.RI "\fInunchuk accelerometer calibration \fP"
.ti -1c
.RI "struct \fBjoystick_t\fP \fBjs\fP"
.br
.RI "\fIjoystick calibration \fP"
.ti -1c
.RI "int * \fBflags\fP"
.br
.RI "\fIoptions flag (points to \fBwiimote_t\&.flags\fP) \fP"
.ti -1c
.RI "\fBbyte\fP \fBbtns\fP"
.br
.RI "\fIwhat buttons have just been pressed \fP"
.ti -1c
.RI "\fBbyte\fP \fBbtns_held\fP"
.br
.RI "\fIwhat buttons are being held down \fP"
.ti -1c
.RI "\fBbyte\fP \fBbtns_released\fP"
.br
.RI "\fIwhat buttons were just released this \fP"
.ti -1c
.RI "float \fBorient_threshold\fP"
.br
.RI "\fIthreshold for orient to generate an event \fP"
.ti -1c
.RI "int \fBaccel_threshold\fP"
.br
.RI "\fIthreshold for accel to generate an event \fP"
.ti -1c
.RI "struct \fBvec3b_t\fP \fBaccel\fP"
.br
.RI "\fIcurrent raw acceleration data \fP"
.ti -1c
.RI "struct \fBorient_t\fP \fBorient\fP"
.br
.RI "\fIcurrent orientation on each axis \fP"
.ti -1c
.RI "struct \fBorient_t\fP \fBa_orient\fP"
.br
.RI "\fIcurrent orientation on each axis (unsmoothed) \fP"
.ti -1c
.RI "struct \fBgforce_t\fP \fBgforce\fP"
.br
.RI "\fIcurrent gravity forces on each axis \fP"
.ti -1c
.RI "struct \fBgforce_t\fP \fBa_gforce\fP"
.br
.RI "\fIcurrent gravity forces on each axis (unsmoothed) \fP"
.in -1c
.SH "Detailed Description"
.PP 
Nunchuk expansion device\&. 
.PP
Definition at line 266 of file wiic_r90/src/wiic/wiic_structs\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for OpenGL Flythrough from the source code\&.
