.TH "nunchuk.h" 3 "Sat Dec 8 2012" "Version 001" "OpenGL Flythrough" \" -*- nroff -*-
.ad l
.nh
.SH NAME
nunchuk.h \- 
.PP
Nunchuk expansion device\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'wiic_internal\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBnunchuk_handshake\fP (struct \fBwiimote_t\fP *wm, struct \fBnunchuk_t\fP *nc, \fBbyte\fP *data, unsigned short len)"
.br
.RI "\fIHandle the handshake data from the nunchuk\&. \fP"
.ti -1c
.RI "void \fBnunchuk_disconnected\fP (struct \fBnunchuk_t\fP *nc)"
.br
.RI "\fIThe nunchuk disconnected\&. \fP"
.ti -1c
.RI "void \fBnunchuk_event\fP (struct \fBnunchuk_t\fP *nc, \fBbyte\fP *msg)"
.br
.RI "\fIHandle nunchuk event\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Nunchuk expansion device\&. 


.PP
Definition in file \fBnunchuk\&.h\fP\&.
.SH "Function Documentation"
.PP 
.SS "void nunchuk_disconnected (struct \fBnunchuk_t\fP *nc)"

.PP
The nunchuk disconnected\&. \fBParameters:\fP
.RS 4
\fInc\fP A pointer to a \fBnunchuk_t\fP structure\&. 
.RE
.PP

.PP
Definition at line 126 of file nunchuk\&.c\&.
.SS "void nunchuk_event (struct \fBnunchuk_t\fP *nc, \fBbyte\fP *msg)"

.PP
Handle nunchuk event\&. \fBParameters:\fP
.RS 4
\fInc\fP A pointer to a \fBnunchuk_t\fP structure\&. 
.br
\fImsg\fP The message specified in the event packet\&. 
.RE
.PP

.PP
Definition at line 138 of file nunchuk\&.c\&.
.SS "int nunchuk_handshake (struct \fBwiimote_t\fP *wm, struct \fBnunchuk_t\fP *nc, \fBbyte\fP *data, unsigned shortlen)"

.PP
Handle the handshake data from the nunchuk\&. \fBParameters:\fP
.RS 4
\fInc\fP A pointer to a \fBnunchuk_t\fP structure\&. 
.br
\fIdata\fP The data read in from the device\&. 
.br
\fIlen\fP The length of the data block, in bytes\&.
.RE
.PP
\fBReturns:\fP
.RS 4
Returns 1 if handshake was successful, 0 if not\&. 
.RE
.PP

.PP
Definition at line 58 of file nunchuk\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for OpenGL Flythrough from the source code\&.
