.TH "orient_t" 3 "Sat Dec 1 2012" "Version 001" "OpenGL Flythrough" \" -*- nroff -*-
.ad l
.nh
.SH NAME
orient_t \- 
.PP
Orientation struct\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <wiic_structs\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "struct \fBang3f_t\fP \fBangle\fP"
.br
.RI "\fIroll, pitch and yaw (this may be smoothed if enabled) \fP"
.ti -1c
.RI "float \fBroll\fP"
.br
.RI "\fIroll, this may be smoothed if enabled \fP"
.ti -1c
.RI "float \fBpitch\fP"
.br
.RI "\fIpitch, this may be smoothed if enabled \fP"
.ti -1c
.RI "float \fByaw\fP"
.br
.ti -1c
.RI "float \fBa_roll\fP"
.br
.RI "\fIabsolute roll, unsmoothed \fP"
.ti -1c
.RI "float \fBa_pitch\fP"
.br
.RI "\fIabsolute pitch, unsmoothed \fP"
.in -1c
.SH "Detailed Description"
.PP 
Orientation struct\&. 

Yaw, pitch, and roll range from -180 to 180 degrees\&. 
.PP
Definition at line 109 of file wiic_r90/src/wiic/wiic_structs\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for OpenGL Flythrough from the source code\&.
