.TH "pressure_weight_t" 3 "Tue Dec 18 2012" "Version 9001" "OpenGL Flythrough" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pressure_weight_t \- 
.PP
Pressure sensor weight struct\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <wiic_structs\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "float \fBtop_left\fP"
.br
.ti -1c
.RI "float \fBtop_right\fP"
.br
.ti -1c
.RI "float \fBbottom_left\fP"
.br
.ti -1c
.RI "float \fBbottom_right\fP"
.br
.ti -1c
.RI "float \fBweight\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Pressure sensor weight struct\&. 

Contains four pressure sensor measurements in Kg\&. Used for the Wii Balance Board\&. 
.PP
Definition at line 177 of file wiic_structs\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for OpenGL Flythrough from the source code\&.
