.TH "pressure_t" 3 "Sun Dec 2 2012" "Version 001" "OpenGL Flythrough" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pressure_t \- 
.PP
Pressure sensor struct\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <wiic_structs\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "unsigned short \fBtop_left\fP"
.br
.ti -1c
.RI "unsigned short \fBtop_right\fP"
.br
.ti -1c
.RI "unsigned short \fBbottom_left\fP"
.br
.ti -1c
.RI "unsigned short \fBbottom_right\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Pressure sensor struct\&. 

Contains four pressure sensor measurements\&. Used for the Wii Balance Board\&. 
.PP
Definition at line 166 of file wiic_structs\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for OpenGL Flythrough from the source code\&.
