.TH "Sample" 3 "Mon Dec 3 2012" "Version 001" "OpenGL Flythrough" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Sample \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBAccSample\fP, and \fBGyroSample\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBsave\fP (ofstream &out)=0"
.br
.ti -1c
.RI "void \fBsetLogType\fP (int l)"
.br
.ti -1c
.RI "int \fBgetLogType\fP () const "
.br
.ti -1c
.RI "void \fBsetTimestampFromGestureStart\fP (unsigned long t)"
.br
.ti -1c
.RI "unsigned long \fBgetTimestampFromGestureStart\fP () const "
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "unsigned long \fBrelTimestamp\fP"
.br
.ti -1c
.RI "int \fBlogType\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 15 of file sample\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for OpenGL Flythrough from the source code\&.
