.TH "Screen" 3 "Sat Dec 8 2012" "Version 001" "OpenGL Flythrough" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Screen \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBScreen\fP (int x, int y)"
.br
.ti -1c
.RI "\fBScreen\fP (const \fBvec2\fP &newSize)"
.br
.ti -1c
.RI "void \fBSize\fP (int x, int y)"
.br
.ti -1c
.RI "void \fBSize\fP (const \fBvec2\fP &newSize)"
.br
.ti -1c
.RI "const \fBvec2\fP & \fBSize\fP (void)"
.br
.ti -1c
.RI "int \fBWidth\fP (void)"
.br
.ti -1c
.RI "int \fBHeight\fP (void)"
.br
.ti -1c
.RI "const \fBvec2\fP & \fBCenter\fP (void)"
.br
.ti -1c
.RI "int \fBMidpointX\fP (void)"
.br
.ti -1c
.RI "int \fBMidpointY\fP (void)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBCameras\fP \fBcamList\fP"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fBvec2\fP \fBsize\fP"
.br
.ti -1c
.RI "\fBvec2\fP \fBcenter\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 8 of file Screen\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for OpenGL Flythrough from the source code\&.
