.TH "speaker.c" 3 "Sat Dec 1 2012" "Version 001" "OpenGL Flythrough" \" -*- nroff -*-
.ad l
.nh
.SH NAME
speaker.c \- 
.PP
Handles the Wiimote speakers\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'wiic_internal\&.h'\fP
.br
\fC#include 'speaker\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBwiic_set_speaker\fP (struct \fBwiimote_t\fP *wm, int status)"
.br
.ti -1c
.RI "void \fBwiic_mute_speaker\fP (struct \fBwiimote_t\fP *wm, int status)"
.br
.ti -1c
.RI "void \fBwiic_sound\fP (struct \fBwiimote_t\fP *wm)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Handles the Wiimote speakers\&. 


.PP
Definition in file \fBspeaker\&.c\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for OpenGL Flythrough from the source code\&.
