.TH "terrain.cpp" 3 "Tue Dec 18 2012" "Version 9001" "OpenGL Flythrough" \" -*- nroff -*-
.ad l
.nh
.SH NAME
terrain.cpp \- 
.PP
This is a derivative of our main project file, \fBfly\&.cpp\fP\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'globals\&.h'\fP
.br
\fC#include <cmath>\fP
.br
\fC#include <cstdio>\fP
.br
\fC#include <sstream>\fP
.br
\fC#include <cstdlib>\fP
.br
\fC#include <time\&.h>\fP
.br
\fC#include 'platform\&.h'\fP
.br
\fC#include 'vec\&.hpp'\fP
.br
\fC#include 'mat\&.hpp'\fP
.br
\fC#include 'model\&.hpp'\fP
.br
\fC#include 'Camera\&.hpp'\fP
.br
\fC#include 'InitShader\&.hpp'\fP
.br
\fC#include 'Cameras\&.hpp'\fP
.br
\fC#include 'Screen\&.hpp'\fP
.br
\fC#include 'Object\&.hpp'\fP
.br
\fC#include 'Timer\&.hpp'\fP
.br
\fC#include 'Scene\&.hpp'\fP
.br
\fC#include 'OpenGL\&.h'\fP
.br

.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef \fBAngel::vec4\fP \fBcolor4\fP"
.br
.ti -1c
.RI "typedef \fBAngel::vec4\fP \fBpoint4\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBTSTATE\fP { \fBSHRINKING\fP, \fBTRANSITIONING\fP, \fBGROWING\fP, \fBDONE\fP }"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBrandomize_terrain\fP ()"
.br
.ti -1c
.RI "void \fBinit\fP ()"
.br
.ti -1c
.RI "void \fBcleanup\fP (void)"
.br
.ti -1c
.RI "void \fBdisplayViewport\fP (void)"
.br
.RI "\fIA function that takes no arguments\&. \fP"
.ti -1c
.RI "void \fBdisplay\fP (void)"
.br
.ti -1c
.RI "void \fBkeylift\fP (unsigned char key, int x, int y)"
.br
.ti -1c
.RI "void \fBMakeFlatToRegular\fP (\fBTransCache\fP &obj)"
.br
.ti -1c
.RI "void \fBkeyboard\fP (unsigned char key, int x, int y)"
.br
.ti -1c
.RI "void \fBkeyboard_ctrl\fP (int key, int x, int y)"
.br
.ti -1c
.RI "void \fBmouse\fP (int button, int state, int x, int y)"
.br
.ti -1c
.RI "void \fBmouseroll\fP (int x, int y)"
.br
.ti -1c
.RI "void \fBwiilook\fP (\fBCamera\fP &WiiCamera, const \fBAngel::vec3\fP &NewTheta, const \fBAngel::vec3\fP &MovementRates)"
.br
.ti -1c
.RI "void \fBmouselook\fP (int x, int y)"
.br
.ti -1c
.RI "void \fBresizeEvent\fP (int width, int height)"
.br
.ti -1c
.RI "void \fBsimpleRotateY\fP (\fBTransCache\fP &obj)"
.br
.ti -1c
.RI "void \fBsimpleRotateAnim\fP (\fBTransCache\fP &obj)"
.br
.ti -1c
.RI "void \fBanimationTest\fP (\fBTransCache\fP &obj)"
.br
.ti -1c
.RI "void \fBidle\fP (void)"
.br
.ti -1c
.RI "void \fBmenufunc\fP (int value)"
.br
.ti -1c
.RI "int \fBmain\fP (int argc, char **argv)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBScreen\fP \fBmyScreen\fP (800, 600)"
.br
.ti -1c
.RI "\fBScene\fP \fBtheScene\fP"
.br
.ti -1c
.RI "GLuint \fBgShader\fP"
.br
.ti -1c
.RI "bool \fBfixed_yaw\fP = true"
.br
.ti -1c
.RI "const char * \fBterrainTex\fP []"
.br
.ti -1c
.RI "TSTATE \fBterrainState\fP = DONE"
.br
.ti -1c
.RI "bool \fBswitchingTerrain\fP = false"
.br
.ti -1c
.RI "float \fBCurrentScale\fP = 0\&.0"
.br
.ti -1c
.RI "float \fBheightScale\fP = 0\&.0"
.br
.RI "\fIhackity hack hack hackey doo! \fP"
.ti -1c
.RI "float \fBticker\fP = 0\&.0"
.br
.in -1c
.SH "Detailed Description"
.PP 
This is a derivative of our main project file, \fBfly\&.cpp\fP\&. 

\fBAuthors:\fP
.RS 4
John Huston, Nicholas StPierre, Chris Compton 
.RE
.PP
\fBDate:\fP
.RS 4
2012-12-06
.RE
.PP
This is a tech demo for terrain generation using an udpated engine derived from \fBfly\&.cpp\fP, which was mostly based on Ed Angel's code from his book\&. 
.PP
Definition in file \fBterrain\&.cpp\fP\&.
.SH "Function Documentation"
.PP 
.SS "void displayViewport (void)"

.PP
A function that takes no arguments\&. Is responsible for drawing a SINGLE VIEWPORT\&. 
.PP
Definition at line 198 of file terrain\&.cpp\&.
.SH "Variable Documentation"
.PP 
.SS "const char* terrainTex[]"
\fBInitial value:\fP
.PP
.nf
 {
  '\&.\&./Textures/GoodTextures_0013423\&.jpg',  
  '\&.\&./Textures/GoodTextures_0013779\&.jpg',  
  '\&.\&./Textures/GrassGreenTexture0002\&.jpg', 
  '\&.\&./Textures/GoodTextures_0013418\&.jpg',  
  '\&.\&./Textures/GoodTextures_0013291\&.jpg'   
}
.fi
.PP
Definition at line 60 of file terrain\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for OpenGL Flythrough from the source code\&.
