.TH "txload" 3 "Tue Dec 18 2012" "Version 9001" "OpenGL Flythrough" \" -*- nroff -*-
.ad l
.nh
.SH NAME
txload \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBtxload\fP (const char *filename, GLuint TextEnum, GLuint gShader, const char *uniform, int num)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const char * \fBfilename\fP"
.br
.ti -1c
.RI "GLuint \fBTextEnum\fP"
.br
.ti -1c
.RI "GLuint \fBgShader\fP"
.br
.ti -1c
.RI "const char * \fBuniform\fP"
.br
.ti -1c
.RI "int \fBnum\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 5 of file LoadTexture\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for OpenGL Flythrough from the source code\&.
