.TH "ir.h" 3 "Sat Dec 1 2012" "Version 001" "OpenGL Flythrough" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ir.h \- 
.PP
Handles IR data\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'wiic_internal\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBWII_VRES_X\fP   560"
.br
.ti -1c
.RI "#define \fBWII_VRES_Y\fP   340"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBcalculate_basic_ir\fP (struct \fBwiimote_t\fP *wm, \fBbyte\fP *data)"
.br
.RI "\fICalculate the data from the IR spots\&. \fP"
.ti -1c
.RI "void \fBcalculate_extended_ir\fP (struct \fBwiimote_t\fP *wm, \fBbyte\fP *data)"
.br
.RI "\fICalculate the data from the IR spots\&. \fP"
.ti -1c
.RI "float \fBcalc_yaw\fP (struct \fBir_t\fP *ir)"
.br
.RI "\fICalculate yaw given the IR data\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Handles IR data\&. 


.PP
Definition in file \fBwiic_v1\&.1/src/wiic/ir\&.h\fP\&.
.SH "Function Documentation"
.PP 
.SS "float calc_yaw (struct \fBir_t\fP *ir)"

.PP
Calculate yaw given the IR data\&. \fBParameters:\fP
.RS 4
\fIir\fP IR data structure\&. 
.RE
.PP

.PP
Definition at line 735 of file wiic_r90/src/wiic/ir\&.c\&.
.SS "void calculate_basic_ir (struct \fBwiimote_t\fP *wm, \fBbyte\fP *data)"

.PP
Calculate the data from the IR spots\&. Basic IR mode\&.
.PP
\fBParameters:\fP
.RS 4
\fIwm\fP Pointer to a \fBwiimote_t\fP structure\&. 
.br
\fIdata\fP Data returned by the wiimote for the IR spots\&. 
.RE
.PP

.PP
Definition at line 317 of file wiic_r90/src/wiic/ir\&.c\&.
.SS "void calculate_extended_ir (struct \fBwiimote_t\fP *wm, \fBbyte\fP *data)"

.PP
Calculate the data from the IR spots\&. Extended IR mode\&.
.PP
\fBParameters:\fP
.RS 4
\fIwm\fP Pointer to a \fBwiimote_t\fP structure\&. 
.br
\fIdata\fP Data returned by the wiimote for the IR spots\&. 
.RE
.PP

.PP
Definition at line 353 of file wiic_r90/src/wiic/ir\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for OpenGL Flythrough from the source code\&.
