.TH "balanceboard.h" 3 "Sat Dec 1 2012" "Version 001" "OpenGL Flythrough" \" -*- nroff -*-
.ad l
.nh
.SH NAME
balanceboard.h \- 
.PP
Balance Board expansion device\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'wiic_internal\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBbalance_board_handshake\fP (struct \fBwiimote_t\fP *wm, struct \fBbalance_board_t\fP *bb, \fBbyte\fP *data, unsigned short len)"
.br
.RI "\fIHandle the handshake data from the balance board\&. \fP"
.ti -1c
.RI "void \fBbalance_board_disconnected\fP (struct \fBbalance_board_t\fP *bb)"
.br
.RI "\fIThe balance board disconnected\&. \fP"
.ti -1c
.RI "void \fBbalance_board_event\fP (struct \fBbalance_board_t\fP *bb, \fBbyte\fP *msg)"
.br
.RI "\fIHandle balance board event\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Balance Board expansion device\&. 


.PP
Definition in file \fBwiic_r90/src/wiic/balanceboard\&.h\fP\&.
.SH "Function Documentation"
.PP 
.SS "void balance_board_disconnected (struct \fBbalance_board_t\fP *bb)"

.PP
The balance board disconnected\&. \fBParameters:\fP
.RS 4
\fIbb\fP A pointer to a \fBbalance_board_t\fP structure\&. 
.RE
.PP

.PP
Definition at line 169 of file wiic_r90/src/wiic/balanceboard\&.c\&.
.SS "void balance_board_event (struct \fBbalance_board_t\fP *bb, \fBbyte\fP *msg)"

.PP
Handle balance board event\&. \fBParameters:\fP
.RS 4
\fIbb\fP A pointer to a \fBbalance_board_t\fP structure\&. 
.br
\fImsg\fP The message specified in the event packet\&. 
.RE
.PP

.PP
Definition at line 107 of file wiic_r90/src/wiic/balanceboard\&.c\&.
.SS "int balance_board_handshake (struct \fBwiimote_t\fP *wm, struct \fBbalance_board_t\fP *bb, \fBbyte\fP *data, unsigned shortlen)"

.PP
Handle the handshake data from the balance board\&. \fBParameters:\fP
.RS 4
\fIbb\fP A pointer to a \fBbalance_board_t\fP structure\&. 
.br
\fIdata\fP The data read in from the device\&. 
.br
\fIlen\fP The length of the data block, in bytes\&.
.RE
.PP
\fBReturns:\fP
.RS 4
Returns 1 if handshake was successful, 0 if not\&. 
.RE
.PP

.PP
Definition at line 40 of file wiic_r90/src/wiic/balanceboard\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for OpenGL Flythrough from the source code\&.
