.TH "guitar_hero_3.h" 3 "Fri Nov 30 2012" "Version 001" "OpenGL Flythrough" \" -*- nroff -*-
.ad l
.nh
.SH NAME
guitar_hero_3.h \- 
.PP
Guitar Hero 3 expansion device\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'wiic_internal\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBGUITAR_HERO_3_JS_MIN_X\fP   0xC5"
.br
.ti -1c
.RI "#define \fBGUITAR_HERO_3_JS_MAX_X\fP   0xFC"
.br
.ti -1c
.RI "#define \fBGUITAR_HERO_3_JS_CENTER_X\fP   0xE0"
.br
.ti -1c
.RI "#define \fBGUITAR_HERO_3_JS_MIN_Y\fP   0xC5"
.br
.ti -1c
.RI "#define \fBGUITAR_HERO_3_JS_MAX_Y\fP   0xFA"
.br
.ti -1c
.RI "#define \fBGUITAR_HERO_3_JS_CENTER_Y\fP   0xE0"
.br
.ti -1c
.RI "#define \fBGUITAR_HERO_3_WHAMMY_BAR_MIN\fP   0xEF"
.br
.ti -1c
.RI "#define \fBGUITAR_HERO_3_WHAMMY_BAR_MAX\fP   0xFA"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBguitar_hero_3_handshake\fP (struct \fBwiimote_t\fP *wm, struct \fBguitar_hero_3_t\fP *gh3, \fBbyte\fP *data, unsigned short len)"
.br
.RI "\fIHandle the handshake data from the guitar\&. \fP"
.ti -1c
.RI "void \fBguitar_hero_3_disconnected\fP (struct \fBguitar_hero_3_t\fP *gh3)"
.br
.RI "\fIThe guitar disconnected\&. \fP"
.ti -1c
.RI "void \fBguitar_hero_3_event\fP (struct \fBguitar_hero_3_t\fP *gh3, \fBbyte\fP *msg)"
.br
.RI "\fIHandle guitar event\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Guitar Hero 3 expansion device\&. 


.PP
Definition in file \fBwiic_r90/src/wiic/guitar_hero_3\&.h\fP\&.
.SH "Function Documentation"
.PP 
.SS "void guitar_hero_3_disconnected (struct \fBguitar_hero_3_t\fP *gh3)"

.PP
The guitar disconnected\&. \fBParameters:\fP
.RS 4
\fIcc\fP A pointer to a \fBclassic_ctrl_t\fP structure\&. 
.RE
.PP

.PP
Definition at line 121 of file wiic_r90/src/wiic/guitar_hero_3\&.c\&.
.SS "void guitar_hero_3_event (struct \fBguitar_hero_3_t\fP *gh3, \fBbyte\fP *msg)"

.PP
Handle guitar event\&. \fBParameters:\fP
.RS 4
\fIcc\fP A pointer to a \fBclassic_ctrl_t\fP structure\&. 
.br
\fImsg\fP The message specified in the event packet\&. 
.RE
.PP

.PP
Definition at line 133 of file wiic_r90/src/wiic/guitar_hero_3\&.c\&.
.SS "int guitar_hero_3_handshake (struct \fBwiimote_t\fP *wm, struct \fBguitar_hero_3_t\fP *gh3, \fBbyte\fP *data, unsigned shortlen)"

.PP
Handle the handshake data from the guitar\&. \fBParameters:\fP
.RS 4
\fIcc\fP A pointer to a \fBclassic_ctrl_t\fP structure\&. 
.br
\fIdata\fP The data read in from the device\&. 
.br
\fIlen\fP The length of the data block, in bytes\&.
.RE
.PP
\fBReturns:\fP
.RS 4
Returns 1 if handshake was successful, 0 if not\&. 
.RE
.PP

.PP
Definition at line 59 of file wiic_r90/src/wiic/guitar_hero_3\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for OpenGL Flythrough from the source code\&.
