.TH "WiiConnect" 3 "Sat Dec 8 2012" "Version 001" "OpenGL Flythrough" \" -*- nroff -*-
.ad l
.nh
.SH NAME
WiiConnect \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "(IOBluetoothL2CAPChannel *) - \fBopenL2CAPChannelWithPSM:device:delegate:\fP"
.br
.ti -1c
.RI "(IOReturn) - \fBconnectToWiimote:\fP"
.br
.ti -1c
.RI "(void) - \fBl2capChannelData:data:length:\fP"
.br
.ti -1c
.RI "(\fBbyte\fP *) - \fBgetNextMsg\fP"
.br
.ti -1c
.RI "(unsigned int) - \fBgetMsgLength\fP"
.br
.ti -1c
.RI "(void) - \fBdeleteMsg\fP"
.br
.ti -1c
.RI "(void) - \fBdisconnected:fromDevice:\fP"
.br
.ti -1c
.RI "(BOOL) - \fBisReading\fP"
.br
.ti -1c
.RI "(void) - \fBsetReading:\fP"
.br
.ti -1c
.RI "(BOOL) - \fBisTimeout\fP"
.br
.ti -1c
.RI "(void) - \fBsetTimeout:\fP"
.br
.ti -1c
.RI "(void) - \fBstartTimerThread\fP"
.br
.ti -1c
.RI "(void) - \fBwakeUpMainThreadRunloop:\fP"
.br
.ti -1c
.RI "(BOOL) - \fBisDisconnecting\fP"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "NSData * \fBreceivedMsg\fP"
.br
.ti -1c
.RI "unsigned int \fBmsgLength\fP"
.br
.ti -1c
.RI "\fBwiimote\fP * \fB_wm\fP"
.br
.ti -1c
.RI "BOOL \fBisReading\fP"
.br
.ti -1c
.RI "BOOL \fBtimeout\fP"
.br
.ti -1c
.RI "BOOL \fBdisconnecting\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 78 of file io_mac\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for OpenGL Flythrough from the source code\&.
